readmeio/oas

packages/examples/3.0/json/readme.json
This lets the OAS document validate.
=> Fix path template in /version/{versionId} path

packages/tooling/__tests__/oas.test.js, packages/tooling/src/oas.js
Added new function for finding operation + test cases
=> Feature(findOperationWithoutMethod): Expose function for resolving URI without method

__tests__/tooling/samples/index.test.js, package-lock.json, package.json, tooling/samples/index.js
=> feat: implementing memoization on sample generation

.eslintrc, __tests__/tooling/index.test.js, tooling/index.js
Oas class changes to support editable server urls component
See unit tests
=> feat: add new methods for server variable support

__tests__/tooling/index.test.js, tooling/index.js
=> feat: allowing the passing of vars into `oas.url()`

__tests__/tooling/operation/get-response-as-json-schema.test.js, tooling/operation/get-response-as-json-schema.js
The description of response headers was in the wrong location. This fixes that.
=> fix(operation): mfix position of header response descriptions

README.md, package.json
=> docs: tiny language tweaks so it's more OpenAPI forward

src/rmoas.types.ts
Adds typescript types to export for server variables
n/a
=> chore: add server variable typescript types

README.md
=> docs: adding a ReadMe badge to the readme

__tests__/index.test.ts, src/index.ts
| 🚥 Fixes #751  |
Automatically call JSON.parse if the type is a string
Do the tests pass? Is my typescript any good? 👍
=> feat: automatically JSON.parse any strings passed into the constructor

__tests__/__datasets__/polymorphism-quirks.json, __tests__/operation/__snapshots__/get-parameters-as-json-schema.test.ts.snap, __tests__/operation/get-parameters-as-json-schema.test.ts, src/lib/openapi-to-json-schema.ts
| 🚥 Resolves RM-8014 |
Currently, when we merge schemas, we don't pass in the `required` array. This makes is so that when an OAS file like the following comes up, the `required` array is cast out and there aren't any required parameters.
<details>
<summary>Nium — allOf with top-level oneOf</summary>
``` json
{
"openapi": "3.0.1",
"info": {
"contact": {
"email": "experience@nium.com",
"name": "NIUM Platform",
"url": "https://www.nium.com"
},
"description": "NIUM Platform",
"license": {
"name": "Copyright (c) 2023 NIUM"
},
"title": "FX",
"version": "1.0"
},
"servers": [
{
"url": "https://gateway.nium.com/n1"
}
],
"paths": {
"/api/v1/client/{clientHashId}/quotes": {
"post": {
"tags": [
"Quotes"
],
"x-info": {
"apiType": "external"
},
"summary": "Create Quote", …
```
=> fix: pass required array into merge schema

__tests__/index.test.ts, __tests__/operation.test.ts, src/index.ts, src/operation.ts, src/utils.ts
| 🚥 Reverts #799 |
25a04c4e4ed4e62c5e621f9f925d1005b0733ff0 / #799 is actually a breaking change 😬 reverting!
=> revert: revert #799

package-lock.json, package.json, src/lib/reducer.ts
Updates all of the following:
```
Package                         Current  Wanted  Latest  Location                                     Depended by
@readme/eslint-config            12.2.0  12.2.1  13.0.1  node_modules/@readme/eslint-config           oas
@types/json-schema               7.0.12  7.0.13  7.0.13  node_modules/@types/json-schema              oas
@types/json-schema-merge-allof    0.6.1   0.6.2   0.6.2  node_modules/@types/json-schema-merge-allof  oas
@types/node                      20.5.9  20.7.0  20.7.0  node_modules/@types/node                     oas
@vitest/coverage-v8              0.34.4  0.34.5  0.34.5  node_modules/@vitest/coverage-v8             oas
eslint                           8.48.0  8.50.0  8.50.0  node_modules/eslint                          oas
oas-normalize …
```
=> chore(deps): bump

packages/oas/src/index.ts, packages/oas/src/operation/index.ts, packages/oas/src/types.ts
Add `getSummary()` and `getDescription()` methods to Webhook class.
=> feat: add getSummary and getDescription methods

packages/oas-to-snippet/src/index.ts, packages/oas-to-snippet/test/__snapshots__/index.test.ts.snap
oops lol (my fault too, i should have looked more closely at the snapshots)
=> fix(oas-to-snippet): use correct val for registry identifier

package-lock.json, packages/oas-to-snippet/package.json, packages/oas-to-snippet/test/__snapshots__/index.test.ts.snap
This pulls in and updates test our Swift snapshots for the `mulitpart/form-data` improvements that @zunda-pixel did over in https://github.com/readmeio/httpsnippet/pull/231.
=> fix(oas-to-snippet): bumping httpsnippet for swift multipart fixes

packages/oas/src/operation/lib/get-callback-examples.ts
Noticed that this could be stronger as part of my work in https://github.com/readmeio/readme/pull/11815.
Does this type successfully pass and does it make sense given the surrounding code?
=> fix(oas): stronger type for callback example

packages/oas/README.md, packages/oas/src/reducer/index.ts
The reducer and analyzer are both super useful tools, even if they do have some drawbacks, but I realized tonight that I never actually documented them. 
🙃
=> docs(oas): writing up docs on `oas/reducer` and `oas/analyzer`

packages/oas/README.md
I moved the `hasRequiredRequestBody` to the Request Body chapter
=> docs: moved method to correct chapter

package-lock.json, tsconfig.base.json
bumps a bunch of dependencies and enables `erasableSyntaxOnly` in all of our `tsconfig.json` files. thankfully no issues were flagged.
before:
```
Package                              Current   Wanted   Latest  Location                                                  Depended by
@apidevtools/json-schema-ref-parser   11.9.2   11.9.3   11.9.3  node_modules/@apidevtools/json-schema-ref-parser          parser@npm:@readme/openapi-parser@3.0.1
@readme/eslint-config                 14.4.1   14.4.2   14.4.2  node_modules/@readme/eslint-config                        oas
@types/node                          22.13.1  22.13.9  22.13.9  node_modules/@types/node                                  oas@26.0.2
@types/node                          22.13.1  22.13.9  22.13.9  node_modules/@types/node …
```
=> chore: `npm up`, enable `erasableSyntaxOnly`

packages/oas-examples/3.0/json/response-empty-examples.json
Adds an 'empty examples' example oas file.
=> feat(oas-examples): add empty examples example

package-lock.json, package.json, packages/har-examples/package.json, packages/http-status-codes/package.json, packages/jest-expect-har/package.json, packages/jest-expect-openapi/package.json, packages/oas-examples/package.json, packages/oas-normalize/package.json, packages/oas-to-har/package.json, packages/oas-to-snippet/package.json, packages/oas/package.json, packages/parser/package.json, vitest.config.mts
| 🚥 Resolves #981 |
```
Package                              Current  Wanted  Latest  Location                                          Depended by
@apidevtools/json-schema-ref-parser   12.0.2  12.0.2  13.0.1  node_modules/@apidevtools/json-schema-ref-parser  parser@npm:@readme/openapi-parser@4.0.1
@vitest/coverage-v8                    3.1.4   3.2.1   3.2.1  node_modules/@vitest/coverage-v8                  oas
@vitest/expect                         3.1.4   3.2.1   3.2.1  node_modules/@vitest/expect                       jest-expect-har@8.0.3
@vitest/expect                         3.1.4   3.2.1   3.2.1  node_modules/@vitest/expect                       jest-expect-openapi@3.0.1
@vitest/expect                         3.1.4   3.2.1   3.2.1 …
```
=> chore(deps): upgrading out of date dependencies
