- lib/generate.js
- lib/print.js
Hello!
I'm using this package and a colorized `generate` breaks my json files. And currently, it is the only way to regenerate a file without running `init` all the time.
So I added a new `print` method to pretty print the output and kept `generate` as simple as possible.
What do you think?
> `generate` without colors

- package-lock.json
- package.json
Running [depcheck](https://www.npmjs.com/package/depcheck), some dependencies that are not used, and have security vulnerabilities, were flagged:
* base-store
* readline-sync
* swagger2-to-postman
* husky
swagger-parser was also flagged, but I'm going to leave it for the time being.
Resolves https://github.com/readmeio/oas/issues/20
> Removing some unused packages.

- __tests__/lib/__snapshots__/parameters-to-json-schema.test.js.snap
- __tests__/lib/parameters-to-json-schema.test.js
- src/lib/parameters-to-json-schema.js
This resolves a bug in our parameter to JSON Schema compilation where body params would always be at the top of the stack instead of the intended ordering of: `path`, `query`, `body`, `cookie`, `formData`, and `header`
> Properly sorting generated JSON Schema representations

- .prettierrc
- __tests__/lib/flatten-array.test.js
- __tests__/lib/flatten-schema.test.js
- package-lock.json
- package.json
- src/lib/flatten-array.js
- src/lib/flatten-schema.js
- utils.js
This pulls over the `flatten` and `flattenResponseSchema` work from [ResponseSchemaBody.jsx](https://github.com/readmeio/api-explorer/blob/master/packages/api-explorer/src/ResponseSchemaBody.jsx) in `@readme/api-explorer`.
Also at the same time, I fixed a bug where if a `type` property was not within a `$ref` component it wouldn't get flattened down.
> feat: pulling over more oas tooling from @readme/api-explorer

- __tests__/oas.test.js
- src/oas.js
Query params were incorrectly being used to generate path match regex. Query strings are now being properly pruned for matching purposes
> Bug Fix - Query Params

- package-lock.json
- package.json
- packages/tooling/__tests__/lib/__snapshots__/parameters-to-json-schema.test.js.snap
- packages/tooling/__tests__/lib/parameters-to-json-schema.test.js
- packages/tooling/src/lib/parameters-to-json-schema.js
Under certain circumstances where an object property would evaluate to `null`, we'd attempt to recurse down into it like an object because `typeof null === 'object`.
I've also added ESLint, Prettier, and our shared ESLint config into the root `package.json` because without it, VSCode wasn't able to find the executables.
> fix: resolving a null assertion issue that broke jsonschema parsing

- .commitlintrc.json
- package-lock.json
- package.json
- packages/tooling/.npmignore
- packages/tooling/__tests__/__fixtures__/lib/json-schema.js
- packages/tooling/__tests__/lib/__snapshots__/parameters-to-json-schema.test.js.snap
- packages/tooling/__tests__/lib/find-schema-definition.test.js
- packages/tooling/__tests__/lib/flatten-schema.test.js
- packages/tooling/__tests__/lib/parameters-to-json-schema.test.js
- packages/tooling/package-lock.json
- packages/tooling/package.json
- packages/tooling/src/lib/find-schema-definition.js
- packages/tooling/src/lib/flatten-schema.js
- packages/tooling/src/lib/parameters-to-json-schema.js
* This is mostly the same code that RJSF uses, just without the recursion to call `find-schema-definition` if we find a nested `$ref`. We handle that case in the code that handles `find-schema-definition` in the Explorer, and though they're probably ripe for a rewrite it's fine for now.
* For `oneOf` and `anyOf` cases, since we can't really flatten down every option defined in those arrays into a single schema that would validate against the document, I'm choosing to just select the first defined object in the set and flatten that out.
```json
"application/xml": {
"schema": "~paths~/pet~post~requestBody~content~application/json~schema"
}
```
> feat: better support for polymorphism

- packages/tooling/__tests__/__fixtures__/lib/json-schema.js
- packages/tooling/__tests__/lib/__snapshots__/parameters-to-json-schema.test.js.snap
- packages/tooling/__tests__/lib/parameters-to-json-schema.test.js
- packages/tooling/src/lib/parameters-to-json-schema.js
This adds support for translating `maxLength` and `minLength` OAS properties to their `maximum` and `minimum JSON Schema counterparts.
> feat: adding support for translating maxLength and minLength props

- packages/tooling/__tests__/lib/parameters-to-json-schema.test.js
- packages/tooling/src/lib/parameters-to-json-schema.js
If we had an object like the following, `lib/parameters-to-json-schema` would error out because there was no `properties` object set with the object.
```json
{
"name": "identities",
"in": "query",
"schema": {
"type": "array",
"items": {
"type": "object",
"additionalProperties": true
}
}
```
> fix: resolve issue where a freeform object couldn't be jsonschema

- packages/tooling/__tests__/lib/parameters-to-json-schema.test.js
- packages/tooling/src/lib/parameters-to-json-schema.js
Since launching v6 of the Explorer, we've gotten a number of reports come through Sentry of OAS documents being used rendered that have `type: array` when they should be `type: object`. It's no fault of ours, but since we can see that they intended for it to be `type: object` as `properties` and not `items` is present on that schema, we can infer and shape the data into what they intended it to be and avoid any fatal rendering errors.
Resolves README-6R in Sentry.
> fix: magically resolving objects that are typod as arrays

- packages/tooling/__tests__/lib/parameters-to-json-schema.test.js
- packages/tooling/package.json
- packages/tooling/src/lib/parameters-to-json-schema.js
This adds some handling for us to be able to repair potentially malformed `array` schemas that we missing an `items` property. Schemas of this kind don't validate OAS, but we have a number of them in our database as it is and they're causing rendering problems.
https://sentry.io/organizations/readme/issues/1574096195/
> fix: adding some handling to repair malformed OAS arrays

- packages/tooling/__tests__/oas.test.js
- packages/tooling/src/oas.js
If the origin URL is the same as the server URL defined in the OpenAPI file, but the path cannot be extracted, it would throw an error in `generatePathMatches()` [here](https://github.com/readmeio/oas/blob/6b58e58bb9ea9928389444421edb0c286d7d2fff/packages/tooling/src/oas.js#L150) since `pathName` is undefined. This fixes that case.
> fix: edge case in findOperation

- packages/tooling/__tests__/lib/parameters-to-json-schema.test.js
- packages/tooling/src/lib/parameters-to-json-schema.js
This resolves a quick with how we're using `parameters-to-json-schema` in `@readme/api-explorer` where if a component schema has a `description`, we'd render it as a `DescriptionField`, resulting in orphaned text that makes the parameters section in our API Explorer confusing.
See:
> fix: removing descriptions from top-level component schemas

- packages/tooling/__tests__/lib/parameters-to-json-schema.test.js
- packages/tooling/src/lib/parameters-to-json-schema.js
This fixes a bug in `parameters-to-json-schema` where if a `requestBody` had a `title` or `description` set, we'd carry it through, resulting in orphan text being displayed in the API Explorer:
This is the same fix as https://github.com/readmeio/oas/pull/153, just for request bodies instead of component schemas.
> fix: bug where requestBody title and descriptions would come through

- packages/tooling/__tests__/oas.test.js
- packages/tooling/src/oas.js
Partially inspired by [`api-explorer`](https://github.com/readmeio/api-explorer/blob/d1df9260c6a7d9d106aa277716fb95d56e5a50fb/packages/oas-to-har/src/index.js#L244-L253).
In the `getHeaders()` function, I'm adding logic to also look in the [`requestBody`](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.3.md#request-body-object) and [`response`](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.3.md#responseObject) objects to see if there are `content` fields that contain [media type objects](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.3.md#mediaTypeObject). If these exist, we can infer `Content-Type` and `Accept` headers and add them to the result.
> feat: look in request/response content when retrieving headers

- packages/tooling/__tests__/__fixtures__/server-variables.json
- packages/tooling/__tests__/oas.test.js
- packages/tooling/src/oas.js
`findOperation()` currently just searches through all of the server URLs, without doing any replacements for server variables.
This fixes that by also including the output of the `url()` function in the list of URLs to search. Not sure if this is the best approach but it seems like the most straightforward.
> fix: include server variables in `findOperation`

- packages/tooling/__tests__/lib/parameters-to-json-schema.test.js
- packages/tooling/src/lib/parameters-to-json-schema.js
This'll resolve some funky OAS/Swagger documents that we've got in our database right now where a `requestBody` schema has a `properties` object, but no adjacent `type`. Since we can infer that it's an object, we should just cast it as one so as to not break JSON Schema parsing that happens on the resulting constructed schema.
> fix: add missing `type` property if missing but has `properties`

- packages/tooling/__tests__/lib/parameters-to-json-schema.test.js
- packages/tooling/src/lib/parameters-to-json-schema.js
If a schema doesn't have a defined `type`, instead of accepting that, we should attempt to do our best to give it a type so it's still valid JSON Schema.
> fix: being more leanient with how we're constructing types

- packages/tooling/__tests__/lib/parameters-to-json-schema.test.js
- packages/tooling/src/lib/parameters-to-json-schema.js
This is a companion part of https://github.com/readmeio/oas/pull/167, but instead of attempting to fix invalid parameter JSO Schema objects, this works on request body and component schemas.
> fix: if a requestBody schema prop has no type, attempt to add one

- packages/tooling/__tests__/__fixtures__/petstore-server-vars.json
- packages/tooling/__tests__/__fixtures__/petstore.json
- packages/tooling/__tests__/oas.test.js
- packages/tooling/src/oas.js
**tl;dr** the test case I added in this PR didn't work with the fix in https://github.com/readmeio/oas/pull/164, but this fix works.
This is a more holistic approach to the problem I was trying to solve in https://github.com/readmeio/oas/pull/164. Instead of just tacking on the populated server URL into the list of server objects to search, this actually populates the variables into the server URLs throughout the entire `findOperation()` process.
I ran into a weird edge case where the base URL doesn't have any server vars but the path does (e.g. `http://petstore.swagger.io/{basePath}`) which would cause [this](https://github.com/readmeio/oas/compare/fix/findOperation-target-server?expand=1#diff-2c461c18e389a6fe7d7b88a13f621987L269) to find the base server object but then not actually …
> fix: populating server vars in findOperation()

- packages/tooling/__tests__/lib/parameters-to-json-schema.test.js
- packages/tooling/src/lib/parameters-to-json-schema.js
This resolves an edge case on parameters where if a parameter contained a nested `allOf`, `anyOf`, or `oneOf` array, we wouldn't add that to the compiled JSON Schema representation, which would result in the parameter not validating.
> fix: bug where a nested allOf/anyOf/oneOf parameter wasn't compiled

- packages/tooling/__tests__/lib/parameters-to-json-schema.test.js
- packages/tooling/src/lib/parameters-to-json-schema.js
Last week I put in a fix to our JSON Schema compilation to add `type: object` on objects if it's missing one and we know that that object has a `properties` object. Problem with this was that this was also being applied to objects that had a properties key named `properties`. This fixes that.
```json
"requestBody": {
"content": {
"application/json": {
"schema": {
"type": "object",
"properties": {
"name": {
"type": "string"
},
"properties": {
"type": "object",
"properties": {
"tktk": {
"type": "integer"
}
}
}
}
}
}
}
}
```
> fix: don't set a type on a properties key if that key is a param

- packages/tooling/__tests__/lib/parameters-to-json-schema.test.js
- packages/tooling/src/lib/parameters-to-json-schema.js
This resolves a bug in our processing of `anyOf`, `oneOf` and `allOf` schemas where in specific cases, we'd add a `type: string` default to it if it were missing a type. This would result in the following broken UI in the API Explorer:
Turns out that trying to repair bad OAS schemas is difficult.
> fix: bug where a string type would be added to anyOf, oneOf, and allOf

- packages/tooling/__tests__/lib/parameters-to-json-schema.test.js
- packages/tooling/src/lib/parameters-to-json-schema.js
| [🎟 Asana](https://app.asana.com/0/681252538274980/1173503272587186/f) |
| :---  |
This resolves an edge case that was introduced in some logic I added to repair schemas without a `type` that was sometimes marking the schema object as a `string`.  This would result in the following "broken" UI:
You can see it in action here:  http://bin.readme.com/s/5eaa651315dd18002423bd32
Now if we remove the `InputErrorResponse`, we'll see that it's resolved:
Now what if you move the `InputErrorResponse` schema below `NewPreauthorization`?
😬 
So the reason this was happening was that since our `cleanupSchemaDefaults` method for `requestBody` and component schema objects is recursive, and we were invoking it against the `components` object, and not individual schemas, it was difficult for us to …
> fix: edge case where component would sometimes be marked a string

- packages/tooling/__tests__/oas.test.js
- packages/tooling/src/oas.js
Server URLs with proceeding whitespace cause HAR validation errors. 🤦
> fix: trim surrounding whitespace in server URLs

- packages/tooling/__tests__/operation.test.js
- packages/tooling/package-lock.json
- packages/tooling/src/operation.js
This method exists currently in `@readme/oas-to-har` but it makes more sense for it to live here.
https://github.com/readmeio/api-explorer/blob/master/packages/oas-to-har/src/index.js#L32-L53
> feat: adding a getContentType method into the OAS Operation class

- packages/tooling/__tests__/oas.test.js
- packages/tooling/src/oas.js
This resolves a bug in `Oas.findOperation` and `Oas.getOperation` where if the defined server URL had a trailing slash, we wouldn't be able to locate an operation within the definition.
> fix: issue where findOperation would fail on server with trailing slash

- packages/tooling/__tests__/operation.test.js
- packages/tooling/src/operation.js
This adds formal support for handling [cookie auth](https://swagger.io/docs/specification/authentication/cookie-authentication/) in `@readme/oas-tooling`.
> feat: properly handle cookie auth

- packages/tooling/__tests__/__fixtures__/multiple-securities.json
- packages/tooling/__tests__/operation.test.js
- packages/tooling/src/operation.js
This resolves an issue with `operation.prepareSecurity()` where if an operation used the same security scheme multiples within an `||` `security` definition, it would be prepared multiple times, resulting in something that looks like the following within the API Explorer:
With this fix, it'll now look like:
> fix: dedupe security schemes when plucking them out of an oas

- packages/tooling/__tests__/oas.test.js
- packages/tooling/src/oas.js
For [Paths Objects](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.1.0.md#pathsObject) that only contain `/`, `findOperation()` wasn't handling trailing slashes properly. For example, the ReadMe API has a `/` endpoint but `findOperation()` will return `undefined` for routes like https://dash.readme.com/api/v1 since it'll look for https://dash.readme.com/api/v1/.
Not sure if this is the best approach but I think it should be fine since [the spec dictates](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.1.0.md#user-content-patterned-fields:~:text=The%20field%20name%20MUST%20begin%20with%20a%20forward%20slash%20(%2F).) the following:
> The field name MUST begin with a forward slash (`/`)
meaning that all paths should contain a `/` at the bare minimum.
> fix: findOperation issues with "/" paths

- packages/tooling/__tests__/operation.test.js
- packages/tooling/src/operation.js
This adds support for resolving `$ref` pointers in `requestBody` when attempting to discover the `Content-Type` header of an operation.
Resolves https://app.asana.com/0/1177947654981875/1175486497688586/f
> fix: add support for $ref when pulling content types

- packages/tooling/__tests__/lib/parameters-to-json-schema.test.js
- packages/tooling/src/lib/parameters-to-json-schema.js
If an operation had a parameter that's defined as a `$ref`, and also had a `requestBody`, there was a chance that we'd remove the `description` property present on the parameter.
> fix: bug where sometimes parameter descriptions would be deleted

- packages/tooling/__tests__/lib/parameters-to-json-schema.test.js
- packages/tooling/src/lib/parameters-to-json-schema.js
This fixes a case where under certain circumstances, `title` properties in polymorphism schemas (`oneOf`, `anyOf`, and `oneOf`) would sometimes be deleted.
This also introduces a workaround for a bug in https://github.com/rjsf-team/react-jsonschema-form where if a `title` property on a `$ref` within one of the aforementioned schemas isn't at the same level as the `$ref`, it's not used when constructing a dropdown picker, resulting in a placeholder that looks like "Option 1".
> fix: case where titles in polymorphism schemas would be removed

- packages/tooling/__tests__/__fixtures__/nested-allof-flattening.json
- packages/tooling/__tests__/lib/flatten-schema.test.js
- packages/tooling/src/lib/flatten-schema.js
This fixes a case where `flattenSchema` wouldn't handle `allOf`, `anyOf`, and `oneOf` cases, resulting in a flattened schema that'd look like:
> fix: flattenSchema not properly flattening allOf/oneOf/anyOf schemas

- __tests__/tooling/lib/flatten-schema.test.js
- package-lock.json
- package.json
- tooling/lib/flatten-schema.js
This completely swaps out the `$ref` parsing engine behind `flattenSchema` with [json-schema-ref-parser](https://github.com/APIDevTools/json-schema-ref-parser)  to allow us to properly, easily, handle circular references without infinitely recusing them.
How it works is we'll funnel an incoming schema and API definition into `json-schema-ref-parser` to dereference it but allowing it to ignore circular refs. If a `$ref` is circular, it'll remain in the schema as `$ref`, enabling us to quickly detect and ignore circular refs when flattening a schema.
With this change, `flattenSchema` is now an async function.
> fix: swapping out the $ref parsing engine of flattenSchema

- cli/lib/utils.js
This PR passes in the `scope` argument to `swagger-inline` so that generated swagger files can be properly scoped.
As per https://github.com/readmeio/swagger-inline#available-options, swagger files can be generated by matching the scope field declared.
No scope
`oas generate VetStore.yaml`
With scope
`oas generate VetStore.yaml --scope public`
Please see repo for example:
https://github.com/kschiu/oas_test
In the `src/` directory,  ran: `oas generate VetStore.yaml > ../no_scope.json`, which generated:
https://github.com/kschiu/oas_test/blob/master/no_scope.json
In the `src/` directory,  ran: `oas generate VetStore.yaml --scope public > ../public_scope.json`, which generated:
https://github.com/kschiu/oas_test/blob/master/public_scope.json
> feat: add scope support to `oas generate` command

- .babelrc
- .eslintignore
- .github/workflows/bundlewatch.yml
- .gitignore
- .prettierignore
- README.md
- package-lock.json
- package.json
- webpack.config.js
The `tooling` sublibrary in this package now ships with some async methods within the `Operation` class, and we've having trouble getting Webpack to compile it properly within our setup. So instead of messing with it further, we're going to instead ship a compiled dist of that library in the published package.
Kind of a pain in the ass, but it works.
> feat: ship a compiled tooling lib dist

- __tests__/tooling/__datasets__/operation-examples.json
- __tests__/tooling/operation/get-requestbody-examples.test.js
- __tests__/tooling/operation/get-response-examples.test.js
- __tests__/tooling/samples/index.test.js
- package-lock.json
- package.json
- tooling/samples/index.js
Adds support for being able to handle generating an example from a schema that has an `allOf`.
> feat: adding support for creating example schemas on allOf schemas

- __tests__/tooling/operation.test.js
- tooling/operation.js
Creates a new `hasRequestBody` method on the `Operation` class to determine if the given operation has a `requestBody` present.
> feat: adding a new hasRequestBody method to the operation

- __tests__/tooling/lib/matches-mimetype.test.js
- __tests__/tooling/operation.test.js
- package-lock.json
- package.json
- tooling/lib/matches-mimetype.js
- tooling/operation.js
- tooling/utils.js
* `getOperationId`
* `getParameters`
* `getResponseByStatusCode`
> feat: adding some new methods to the operation class

- __tests__/tooling/operation.test.js
- tooling/operation.js
Adds a new `hasOperationId` accessor on the `Operation` class for determining if an `operationId` is present in the operation schema or not.
> feat: adding a new hasOperationId accessor on the operation class

- __tests__/tooling/lib/flatten-schema.test.js
- tooling/lib/flatten-schema.js
> feat: flattenSchema now expects a fully dereferenced schema

- CHANGELOG.md
- __tests__/tooling/operation/get-parameters-as-json-schema.test.js
- package.json
- tooling/operation.js
- tooling/operation/get-parameters-as-json-schema.js
This resolves a regression that was introduced in https://github.com/readmeio/oas/pull/301 that affected how we were able to construct common parameters when using `getParametersAsJsonSchema`. The problem it turns out is that by changing how we were storing operation schema data to a `schema` property in the `Operation` class, we were no longer supplying `getParametersAsJsonSchema` with the current `path` needed to find common parameters in the OAS.
This issue was also compounded by us having tests for common parameters that were generating false positives by supplying the `oas` in the wrong part of the schema it should have been in.
To resolve this, I've rewritten a couple things:
> fix: regression of common parameters support in JSON Schema generation

- .eslintrc
- __tests__/tooling/__snapshots__/index.test.js.snap
- __tests__/tooling/index.test.js
- tooling/index.js
> feat: implementing blocking on `oas.dereference` to prevent multiple executions

- __tests__/tooling/operation/get-parameters-as-json-schema.test.js
- tooling/operation/get-parameters-as-json-schema.js
> fix: catch jsonpointer errors when looking for jsonschema examples

- __tests__/tooling/operation/get-parameters-as-json-schema.test.js
- tooling/operation/get-parameters-as-json-schema.js
Fixes a bug in our examples lookup work where if `examples: {}` was present we'd crash because we're expecting `value` to be inside one of the keyed properties of it.
> fix: prevent us from crashing if `examples` is an empty object

- __tests__/tooling/index.test.js
- tooling/index.js
If you do `oas.operation(path, method)` and that path+method combination isn't found in the attached OAS, we still return an empty `Operation` class. Problem though is that we aren't prefilling the `schema` property on that class with anything so if you try to use any of the accessors on that class, like `Operation.getResponseBody()`, they'll fail because `schema` is `undefined`.
> fix: operation being set to undefined if not found

- __tests__/tooling/lib/flatten-schema.test.js
- tooling/lib/flatten-schema.js
This fixes a bug in our `flattenSchema` library where if an array description was located inside of the `items` object, we wouldn't retain it.
Fixes RM-232
```js
{
type: 'object',
properties: {
products: {
type: 'array',
items: {
description: 'product schema description', // This description wouldn't be retained and `products` 
// would be set with an `undefined` description.
type: 'object',
properties: {
cash: {
description: 'cash schema description',
type: 'object',
properties: {
accounts: {
type: 'array',
items: {
description: 'account schema description',
type: 'object',
properties: {
id: {
type: 'string',
description: 'account id',
},
},
},
},
},
},
},
},
},
},
}
```
> fix: issue where flattened array descriptions wouldn't be retained

- __tests__/tooling/operation/get-parameters-as-json-schema.test.js
- tooling/operation/get-parameters-as-json-schema.js
With the rewrite of `getParametersAsJsonSchema()` #358 we lost support for parameter `content` schemas, something we never actually officially supported or had tests for.
```json
{
"name": "groupId",
"description": "Filter the data by groupId",
"in": "query",
"required": false,
"content": { "application/json": { "schema": { "type": "string" } } }
}
```
Fixes [RM-311](https://linear.app/readme-io/issue/RM-311/we-are-trying-to-render-params-we-dont-understand)
I've added in a bunch of different test cases, but the ways we support this and pick up schemas within `content` are as follows:
* If there is just a single content type in `content` we'll pick that up and use the schema inside it.
* If there are two non-`application/json` content types in `content` we'll use the first in the list.
* …
> fix: adding support for parameter `content` schemas

- __tests__/tooling/operation/get-parameters-as-json-schema.test.js
- tooling/operation/get-parameters-as-json-schema.js
@rafegoldberg stumbled on this in the [AWS Workspaces](https://preview.readme.io/?selected=https%3A%2F%2Fapi.apis.guru%2Fv2%2Fspecs%2Famazonaws.com%2Fworkspaces%2F2015-04-08%2Fopenapi.json) definition while testing out https://github.com/readmeio/api-explorer/pull/1179, but we have an edge case right now where if you're using `allOf` to dynamically add a `description`, and only that, to another schema, we'll add `type: string` to the description object.
For example:
```js
allOf: [
{ 
type: 'array', 
items: { 
type: 'string' 
}
}, 
{ description: 'Parameter description' } // This ends up receiving `type: string`.
],
```
Reason why this ends up failing in the API Explorer is because when `@readme/oas-form` attempts to merge the schemas in the `allOf`, `array` and `string` collide and …
> fix: edge case where allOfs would receive a `type` when one wasn't present

- __tests__/tooling/operation/get-response-examples.test.js
- tooling/lib/get-mediatype-examples.js
Fixes a bug where if a media type in a response had a `value: null` we'd throw an exception while trying to look for a `$ref` in it.
> fix: exception that would be thrown when trying to access a null example

- __tests__/tooling/__fixtures__/multiple-securities.json
- __tests__/tooling/lib/get-auth.test.js
- tooling/index.js
- tooling/lib/get-auth.js
This adds a new `getAuth()` method on the OAS class that can be used to pull back an object of auth data for use in `@readme/oas-to-har`.
The code for this currently exists in https://github.com/readmeio/api-explorer/blob/next/packages/api-explorer/src/lib/get-auth.js, but this is a better place for it.
See unit tests.
> feat: addition of a new `getAuth` method on the OAS class

- .github/workflows/bundlewatch.yml
- .github/workflows/ci.yml
- .github/workflows/codeql-analysis.yml
- package-lock.json
- package.json
> ci: requiring npm@7 for local development

- __tests__/tooling/samples/index.test.js
- tooling/samples/index.js
- tooling/samples/utils.js
| [Linear Ticket](https://linear.app/readme-io/issue/CX-183/allof-property-causes-display-issue) |
|------------------------------------------------------------------------------------------------|
This PR adds support to render responses that are currently using polymorphism. 
The operation with the response:
The respective components:
We currently render the response example in the above operation like so:
As you can see, the `reach` parameter is using `allOf`, although it is a weird use of `allOf`, but we don't render the object that `reach` is referencing. 
With these changes, we're correctly grabbing the `properties` object from the schema to show the following:
1. Use the OA file in the Linear ticket or the one on my [test project](https://darren.readme.io/openapi/60497c0392b39a0065e …
> feat: support polymorphistic response examples

- __tests__/tooling/operation.test.js
- tooling/operation.js
As part of the changes I made in https://github.com/readmeio/readme/pull/3811, I wrote a little helper function [here](https://github.com/readmeio/readme/blob/b2b01ecbfe0a3c82c847aefb3ce0eaf711afe7b3/packages/react/src/ui/APIAuth/index.jsx#L70-L72) that uses some of the logic we use in [`operation.prepareSecurity()`](https://github.com/readmeio/oas/blob/7d5c1575ef1dcf6b9913657c89f3c5dbaf404bb6/tooling/operation.js#L122) for validating and setting types for security schemes (while maintaining the array structure so multiple auth grouping is preserved). That function should probably live in this library instead.
I simply extracted that part of the `prepareSecurity()` function into its own function (and added a tiny flag for filtering out junk)—hence I'm considering this a refactor, but it …
> refactor: extract part of prepareSecurity() function into a new function

- __tests__/tooling/operation.test.js
- __tests__/tooling/operation/get-response-as-json-schema.test.js
- tooling/operation.js
- tooling/operation/get-response-as-json-schema.js
We're hoping to render response schemas more similarly to request schemas, so this adds the ability to extract response data that looks like our request schemas.
See the tests!
> Adds the ability to extract response data similar to getParametersAsJsonSchema

- __tests__/tooling/operation/get-response-as-json-schema.test.js
- package.json
- tooling/operation/get-response-as-json-schema.js
The old way of surfacing response descriptions was more accurate in the big picture, so this changes it back.
> fix: revert repositioning of description

- __tests__/tooling/__datasets__/operation-examples.json
- __tests__/tooling/operation/get-response-examples.test.js
- tooling/operation/get-response-examples.js
This is going to require some updates to `@readme/api-explorer` and the Reference Redesign to account for this work, but this'll allow those codebases access to this data.
See attached unit tests.
> feat: adding support retrieving 204/empty responses

- __tests__/tooling/index.test.js
- tooling/index.js
This'll fix an edge-case where if an OAS server is `//petstore.example.com` and you pass `Oas.getOperation('https://petstore.example.com/', 'GET')` `getOperation()` would return `undefined`.
> fix: adding support for matching schemeless OAS server urls

- __tests__/tooling/index.test.js
- tooling/index.js
This was being surfaced in our `APIServers` component where because we do `findOperation` lookups in a handful of spots to be able to handle servers with variables, our `findOperationMatches` code was actually overwriting the core `servers` data within the OAS, resulting in complete data loss of these servers variables. 
Because apparently of this:
```js
const servers = [{ url: 'https://example.com' }];
const found = servers.find(server => server.url === 'https://example.com');
found.url = 'https://google.com';
console.log(servers[0].url); // https://google.com
```
🤡 
See the unit test I added.
> fix: edgecase where server urls would get corrupted with normalized versions

- __tests__/tooling/index.test.js
- tooling/index.js
This is a weird one!
Say you have an OAS that has a server URL of `https://{region}.node.example.com/v14` and a logged in user JWT with `region` set to `us`. `region` is an enum that can be either `us` or `eu`. Now say you're trying to find an operation for https://eu.node.example.com/v14/api/esm. Won't work.
The way we do operation discovery (with `getOperation()` and `findOperation()`) is we run through a checklist of things to look for:
1. First we replace the server URL with the users variables so https://{region}.node.example.com/v14 becomes https://us.node.example.com/v14
2. Then we look at the origin of the URL we're looking for: https://us.node.example.com
3. If that fails we fallback to the hostname we're looking for: us.node.example.com
4. If we've got a match, split our found …
> fix: quirks with operation discovery on servers that have variables

- __tests__/tooling/index.test.js
- package-lock.json
- tooling/index.js
This handles an oas with a server URL that has no host or domain, such as `/api/v3`. An example of this can be found in the `server` specified in this petstore v3 [oas](https://petstore3.swagger.io/api/v3/openapi.json).
> Handle Oas with a server URL that has no host or domain

- __tests__/lib/get-auth.test.js
- src/lib/get-auth.js
Allows consumers of this package to more easy distinguish between an empty oas file and empty user input.
Updated the tests so they pass.
- Whenever we integrate this into the `api-explorer` package, there are some [tests](https://github.com/readmeio/api-explorer/blob/main/packages/api-explorer/__tests__/lib/get-auth.test.js) that may need to be updated. I don't see any code in that project that seems like this it will be affected by this change.
- There are some places in the ReadMe project that explicitly check for empty strings that likely need to updated.
- [SelectWidget](https://github.com/readmeio/readme/blob/next/packages/schema-form/src/Form/components/widgets/SelectWidget.js#L103)
- [BaseInput](https://github.com/readmeio/readme/blob/next/packages/schema-form/src/Form/components/w …
> feat: use null instead of empty-string for empty state

- __tests__/operation/get-parameters-as-json-schema.test.js
- src/operation/get-parameters-as-json-schema.js
This adds some handling for objects that have no `properties`, `additionalPropeties`, and aren't polymorphic, to rewrite their schemas as being `additionalProperties` objects so that when we handle them in our form system we'll be able to generate inputs for the user.
This'll help resolve RM-1256.
For example the following object schema:
```js
{
type: 'object'
}
```
will be rewritten into becoming the following when we construct JSON Schema:
```js
{
type: 'object'
additionalProperties: true
}
```
> fix: treat objects without any properties as `additionalProperties` 

- __tests__/operation/get-parameters-as-json-schema.test.js
- src/operation/get-parameters-as-json-schema.js
Currently, for parameters, we don't pass in `current.name` as `currentLocation` to `constructSchema`. This makes it so that when we get into `consructSchema`, `currentLocation` will be blank for the first iteration.
This change makes it so `currentLocation` will be correct for each iteration of parameters.
This is mostly to fix user defined JWT defaults not working for path, query and header parameters. I can provide testing steps when I open the PR in the main repo.
> fix: update getParameters to pass parameter name to constructSchema

- __tests__/__fixtures__/path-matching-quirks.json
- __tests__/index.test.js
- src/index.js
This fixes a quirk in our `findOperation()` method where if a path in the API definition had a query param (like `?param=123` it would completely kill the method because the `?` was being interpreted as a regex modifier for [path-to-regexp](http://npm.im/path-to-regexp). To resolve this, I've loosened up matching on these kinds of paths so it'll look on `/path` instead of `/path?param=123`.
Fixes RM-1396
I've added test cases for the initial regression as well as some other potential variants of this quirk.
> fix: quirk where a path with a query string would break matching

- __tests__/index.test.js
- src/index.js
This fixes a bug with `findOperation` where if an API definition didn't have any defined `servers` we wouldn't be able to match any operation within it.
Fixes RM-1425
See attached test.
> fix: path matching quirk in oas files missing servers

- __tests__/index.test.js
- src/index.js
This fixes a bug in `Oas.findOperation()` where if a defined API definition server url had variable casing we wouldn't be able to match it if the `uri` being passed into `findOperation` was all lowercased.
I've added tests for this original case of the server not matching the incoming URL, but also the reverse situation.
> fix: bug where variable-casing in servers and urls would break path matching

- __tests__/__datasets__/readonly-writeonly.json
- __tests__/operation/get-requestbody-examples.test.js
- __tests__/operation/get-response-examples.test.js
- src/lib/get-mediatype-examples.js
- src/operation/get-requestbody-examples.js
- src/operation/get-response-examples.js
> feat: adding support for showing/hiding readOnly and writeOnly example props

- __tests__/__fixtures__/polymorphism-quirks.json
- __tests__/operation/get-parameters-as-json-schema.test.js
- src/operation/get-parameters-as-json-schema.js
This updates our `getParametersAsJsonSchema` library to improve some of its handling with `properties` and polymorphic `oneOf` schemas that are at the same level. That's a lot of goobledegook, let me explain.
See the following schema:
In this there's a `properties` object and a `oneOf` array at the same level within the `exclusiveRequirements` object. Currently when we process this schema the `properties` object is left alone because it's fully formed but we add a `type: string` into each of the options within the `oneOf` because we think that they're malformed schemas. The result of this when we render it within ReadMe is this:
Instead what this schema is actually trying to tell us is that `exclusiveRequirements` can be either the `properties` object with `requiredOne` as required or the …
> feat: improved handling of same-level properties and oneOf's

- __tests__/__datasets__/readonly-writeonly.json
- __tests__/operation/get-response-examples.test.js
- src/lib/get-mediatype-examples.js
- src/samples/index.js
This fixes a bug in our core `sampleFromSchema` handling for request and response example generation where if you ran one before the other, schemas that are either `readOnly` or `writeOnly` would be excluded when they should normally be present. This was happening because the object we were passing into `sampleFromSchema` was being passed as a reference and that code updates the schema object, which was then propagating back upstream to the `Operation` class instance.
I'm also adding support for `format: YYYY-MM-DD` because I noticed a spec we have has that instead of the more common `format: date`.
Fix in support of RM-1765.
See added tests.
> fix: bug where request or response example fetching would update the operation schema

- __tests__/__datasets__/circular.json
- __tests__/__fixtures__/create-oas.js
- __tests__/index.test.js
- __tests__/lib/openapi-to-json-schema.test.js
- __tests__/operation/__snapshots__/get-parameters-as-json-schema.test.js.snap
- __tests__/operation/__snapshots__/get-response-as-json-schema.test.js.snap
- __tests__/operation/get-parameters-as-json-schema.test.js
- __tests__/operation/get-response-as-json-schema.test.js
- __tests__/operation/get-response-examples.test.js
- src/lib/openapi-to-json-schema.js
- src/operation/get-parameters-as-json-schema.js
- src/operation/get-response-as-json-schema.js
This makes a few minor, but important, changes to `Operation.getParametersAsJsonSchema()` with regard to how it handles `$ref` pointers and some problems it's got therein:
* If a `parameter` schema utilized a `$ref` pointer, and that pointer remained after dereferencing (implying that it's circular), we would previously not copy that component into the resulting JSON Schema leading to a JSON Schema to at has a `$ref` pointer to something that doesn't exist.
* If a `requestBody` exists, and there are `components` in the API definition we would always copy those components into the JSON Schema for that request body. Always.
With this work we now only include `components` if `$ref` pointers are discovered while constructing JSON Schema for parameters, request bodies, and responses.
What's …
> perf: only include components if circular $ref pointers are in the JSON Schema

- __tests__/__datasets__/discriminators.json
- __tests__/operation/__snapshots__/get-parameters-as-json-schema.test.js.snap
- __tests__/operation/get-parameters-as-json-schema.test.js
- src/lib/openapi-to-json-schema.js
This fixes a problem introduced in https://github.com/readmeio/oas/pull/479 where `discriminator` `mapping` component schemas weren't being included in generated JSON Schema because those aren't defined with a traditional `$ref` property.
See tests.
> fix: including refs when discriminator mappings are present

- __tests__/__datasets__/complex-nesting.json
- __tests__/__snapshots__/index.test.js.snap
- __tests__/index.test.js
- __tests__/operation/__snapshots__/get-parameters-as-json-schema.test.js.snap
- __tests__/operation/get-requestbody-examples.test.js
- __tests__/operation/get-response-as-json-schema.test.js
- src/index.js
With the work I did in #479, I accidentaly broke some functionality in our form generator where for an `anyOf` or `oneOf` schema we use the name of the component schema if there isn't a `title` present. Since those schemas are no longer always present we need an alternative way to expose what the schema *was* called, and we're doing that now with this `x-readme-ref-name` extension.
Pre-dereferencing we now run through all component schemas and note what their name is so that when we dereference that metadata will be preserved wherever that schema `$ref` is utilized.
See tests.
> feat: preserving ref schema names during dereferencing

- __tests__/__datasets__/readonly-writeonly.json
- __tests__/__snapshots__/operation.test.js.snap
- __tests__/operation/get-requestbody-examples.test.js
- __tests__/operation/get-response-examples.test.js
- src/samples/index.js
Fixes a quirk with `readOnly` and `writeOnly` where if they were within a schema that was in an `allOf` we wouldn't include them in generated examples.
Fixes RM-1765
See tests.
> fix: quirk with request/response examples where readonly/writeonly was ignored in allOf

- .npmignore
- .prettierignore
- __tests__/__snapshots__/operation.test.js.snap
- __tests__/lib/openapi-to-json-schema.test.js
- __tests__/operation/__snapshots__/get-parameters-as-json-schema.test.js.snap
- __tests__/operation/get-parameters-as-json-schema.test.js
- __tests__/operation/get-response-as-json-schema.test.js
- src/lib/openapi-to-json-schema.js
This updates our JSON Schema generation to constrain known `integer` and `number` formats within the limits defined by their formats. These include:
| Type | Format |
| :--- | :--- |
| integer | int8 |
| integer |  int8 |
| integer | int16 |
| integer | int32 |
| integer | int64 |
| integer | uint8 |
| integer | uint16 |
| integer | uint32 |
| integer | uint64 |
| number | float |
| number | double |
Fix in support of RM-1716.
See tests.
> feat: constrain integer and number formats when generating JSON Schema

- __tests__/operation/get-response-as-json-schema.test.js
- src/operation/get-response-as-json-schema.js
This adds support to `Operation.getResponseAsJsonSchema()` to return JSON Schema for content/media types that aren't JSON-compatible.
I'm not sure why I originally introduced this restriction but it doesn't make sense because JSON Schema generation isn't clamped down to only JSON. If you you have a response that returns `image/png` and a schema of `type: string` we can still generate functional JSON Schema for that. 
For example, this operation returns `*/*` and right now we render:
We're already able to handle non-JSON media types properly within `getParametersAsJsonSchema()` already, just we prefer JSON over everything else and if we don't have JSON we'll use what we have. That flow is now being utilized within `getResponseAsJsonSchema`. 
Fix in support of RM-2075.
See tests.
> fix: support generating response json schema for non-json content types

- __tests__/operation/get-response-as-json-schema.test.js
- src/operation/get-response-as-json-schema.js
This fixes a bug in our `Operation.getResponseAsJsonSchema()` method where if a response had an empty `content` object present, `getResponseAsJsonSchema` would crash.
See tests.
> fix: improper handling of empty response content objects

- __tests__/operation.test.js
- src/operation.js
Adds a new `.getTags()` method to the `Operation` class that will pull back tags, and their OAS-level defined metadata, for the current operation.
See tests.
> feat: adding a new `getTags` method to the operation class

- __tests__/operation/__snapshots__/get-parameters-as-json-schema.test.js.snap
- __tests__/operation/get-parameters-as-json-schema.test.js
- src/operation/get-parameters-as-json-schema.js
Required params were getting put under the accordion along with everything else, this stops them from being pulled so we aren't hiding anything that is top-level required. Works by checking to make sure the param doesn't exist in the `required` array in the schema before pulling & deleting it 
see tests (refactored some + added test to check for required params)
> refactor: don't pull required deprecated params out to deprecatedProps

- __tests__/__snapshots__/index.test.js.snap
- __tests__/index.test.js
- __tests__/lib/openapi-to-json-schema.test.js
- __tests__/operation.test.js
- __tests__/operation/get-parameters-as-json-schema.test.js
- src/index.js
- src/lib/get-auth.ts
- src/lib/get-schema.js
- src/operation.js
- src/operation/get-parameters-as-json-schema.js
- src/operation/get-response-as-json-schema.js
This changes how the core `Oas` class internally stores its API definition from storing it as an extension of `this` (making the instance the API definition essentially) to storing that API definition inside of a new `api` property.
Why do this? As we're slowly typing the library with Typescript it's become more and more of a problem to type the this `Oas` class as a mix of `Oas` and `OpenAPI.Document`, and there are a lot of hoops, that are likely going to be flaky, that we've had to jump through to get it sort of functional. This refactor should make this Typescript transition a little smoother.
This will be a breaking change when it's eventually published.
Tests all still pass?
> refactor: changing how the Oas class internally stores its API definition

- __tests__/index.test.ts
- __tests__/lib/get-auth.test.ts
- __tests__/operation.test.ts
- __tests__/operation/get-callback-examples.test.ts
- __tests__/operation/get-requestbody-examples.test.ts
- __tests__/operation/get-response-examples.test.ts
- package.json
- src/index.ts
- src/operation.ts
- src/rmoas.types.ts
> feat: addition of an `init` and methods for pulling spec extensions

- __tests__/operation/get-response-as-json-schema.test.js
- src/operation/get-response-as-json-schema.js
This fixes a bug in our `getResponseAsJsonSchema()` library where if a [response header](https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.0.3.md#headerObject) had a description it wouldn't get picked up into the compiled JSON Schema representation.
Fix in support of RM-2778.
See tests.
> fix: exposing response header descriptions in response json schema

- __tests__/__snapshots__/operation.test.ts.snap
- __tests__/lib/openapi-to-json-schema.test.ts
- __tests__/operation/__snapshots__/get-parameters-as-json-schema.test.js.snap
- __tests__/operation/get-parameters-as-json-schema.test.js
- src/operation/get-parameters-as-json-schema.ts
This moves the `$schema` identifier applied to json schemas to a more accessible location for the frontend.
It also adds it to deprecated params
Tests
> fix(jsonschema): move the  version identifier to a better location

- package-lock.json
- package.json
Upgrades `oas-normalize` and its dependency on `@readme/openapi-parser` to fix a rare NPM installation issue where Git might not be available.
Fix in support of https://github.com/readmeio/rdme/issues/401.
If tests still all pass this is good to go.
> fix: upgrading oas-normalize to fix a rare npm installation issue

- __tests__/ts-quirks.test.js
Adds a regression case for the `[...Set(['1', '2'])` case that hit us last night in production.
See https://github.com/readmeio/oas/pull/559 for details.
> test: adding a regression case for the enum typescript quirk

- __tests__/operation.test.ts
- src/operation.ts
Adds two new accessors to `Operation` (and `Callback`) instances:
> feat: adding accessors for operation summary and description

- __tests__/__datasets__/parameters-common.json
- __tests__/operation.test.ts
- src/index.ts
- src/operation.ts
- src/utils.ts
> fix: improved support for common params

- __tests__/__datasets__/callbacks.json
- __tests__/operation.test.ts
- src/operation.ts
This fixes a regression I introduced in #563 where if you execute either `getSummary()` or `getDescription()` on a `Callback` instance they would fail because the callback doesn't have access to the root `path` data for `this.api.paths`.
To fix this I've overridden the two methods in the `Callback` class to utilize a new `parent` data that the `Callback` constructor now requires so all callbacks have access to their immediate parent [path item object](https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.0.3.md#pathItemObject) where common summary and description information is stored.
This was a doozy to brain out.
I've merged the `getSummary()` and `getDescription()` tests into a single block because they were both loading the same operations for their tests -- should …
> fix: callbacks not having path-level data to retrieve common summaries

- __tests__/operation.test.ts
- src/operation.ts
Adds a new `getRequestBody` accessor on the `Operation` object that pulls back a request body [Media Type Object](https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.1.0.md#mediaTypeObject) for any specific media type that's present on the operation.
This isn't going to be used anywhere just yet but when we refactor/rewrite the `getSchema()` library here it can be used there.
See tests.
> feat: addition of a getRequestBody accessor

- __tests__/samples/index.test.ts
- src/samples/index.ts
When there's no example present, right now we just autofill the example sample with the type. This will use the default if it exists before falling back to a generic type-based sample 
I used how we were taking the default for booleans over a generic value and turned it into a reusable function to either use the default if it 1) exists and 2) is the right type, otherwise it falls back onto a provided generic value 
The type check probably isn't super necessary, but on the off chance someone tries to use a wacky default hopefully it'll prevent something from breaking
see tests
> refactor: use default for samples over generic type

- __tests__/lib/openapi-to-json-schema.test.ts
- __tests__/samples/index.test.ts
- src/lib/openapi-to-json-schema.ts
- src/operation/get-parameters-as-json-schema.ts
This doesn't fix any bugs but rather a type issue discovered in #581 where when we store examples in the `openapi-to-json-schema` `prevSchemas` object we were storing them as the OpenAPI Schema Object, which is an object of objects, when it was actually expecting an array of objects.
It's difficult to properly explain but check out https://github.com/readmeio/oas/pull/581#discussion_r785599642 for the TS error that uncovered this.
> fix: funky typing with how we extract examples during JSON Schema generation

- __tests__/__datasets__/operation-examples.json
- __tests__/operation/get-response-examples.test.ts
- src/operation/get-response-examples.ts
If we're creating response examples and there's no examples/we can't generate examples because there's no content but there's headers
- Status codes without content that have headers now get an empty `mediaType ` with the type of wildcard `*/*`
- A boolean will get passed on these statuses indicating that they only have headers (which will be used on the front end)
The handling of populating an example for these using the status code + status message [will take place in our Response react component](https://github.com/readmeio/readme/pull/6101) 👍 This PR is to just get the data there 
Tests are passing
> fix: show response headers w/o mediaType content

- __tests__/__snapshots__/index.test.ts.snap
- __tests__/index.test.ts
- src/index.ts
In working on codegen in [api](https://npm.im/api) I want to generate Typescript types with the original `$ref` names but the library I'm using [json-schema-to-typescript](https://npm.im/json-schema-to-typescript) doesn't offer any flexibility other than using the `title` present in the JSON Schema; and since we're preserving `$ref` pointers during the dereference process to an `x-readme-ref-name` extension I can't use this data.
This adds a new option to the `dereference` method to allow me to override any present `title` in schemas with the original `$ref` name. It may result in some data loss but in the end I think that with this codegen the types will be cleaner with the original ref names than whatever `title` was originally present within the schema.
See tests.
> feat: adding a dereference option to preserve ref pointers as titles

- __tests__/tsconfig.json
- jest.config.js
- tsconfig.test.json
VSCode doesn't support `testconfig.*.json` configs but colocating our testing tsconfig with tests seems to make it work.
> test: colocating the testing tsconfig with the tests

- package-lock.json
- package.json
- src/cli/lib/utils.js
Incorporating the work that @garret-wade did in https://github.com/readmeio/swagger-inline/pull/249 the `oas` now has the ability to specify custom [multilang-extract-comments](https://npm.im/multilang-extract-comments) with a `--pattern` argument as well as a new `--pathGlob` argument for customizing where to look for an OAS file.
Resolves https://github.com/readmeio/oas/issues/603
> feat: upgrading swagger-inline and adding new `pathGlob` and `pattern` options

- __tests__/operation.test.ts
- src/operation.ts
We're currently generating URL slug-like operation IDs when one isn't present, and we use this work in `api` and for operations that don't have an operation ID it makes the UX of calling one of these operations really gnarly:
```js
api['get-pets']().then(res => console.log('json response:', res))
```
With this work we'll be able to generate friendlier ones:
```js
api.getPets().then(res => console.log('json response:', res))
```
See tests.
> feat: optionally generate friendlier operationIds

- __tests__/operation.test.ts
- src/operation.ts
This adds two new Operation accessors:
`hasRequiredParameters` simply looks at the operations parameters (or common parameters if they're present) and reports back if any of them contain `required: true`. `hasRequiredRequestBody` does the same, but handles a couple situations:
1. If a [Request Body Object](https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.1.0.md#requestBodyObject) has `required: true` we'll report that its request body is required.
2. If that [Request Body Object](https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.1.0.md#requestBodyObject) has `required: false` but the [Schema Object](https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.1.0.md#schemaObject) within its primary [Media Type …
> feat: adding new accessors for determining if an operation has required params

- __tests__/__fixtures__/create-oas.ts
- __tests__/operation/__snapshots__/get-parameters-as-json-schema.test.ts.snap
- __tests__/operation/get-parameters-as-json-schema.test.ts
- __tests__/utils.test.ts
- src/operation.ts
- src/operation/get-parameters-as-json-schema.ts
- src/rmoas.types.ts
This adds a couple new options to `getParametersAsJsonSchema` (and reworks the method signature into accepting an options object).
Because I am changing the method signature of `getParametersAsJsonSchema` this work will incur a breaking change release.
So for some background, in [api](https://npm.im/api) method signatures consist of two arguments: `body` and `metadata`. `body` is comprised of request body payloads, and `metadata` is comprised of everything else (query params, headers, path, and cookies).
Within the SDK code generation project I'm working on in RM-3414 I need to insert auto-generated Typescript parameter interfaces into methods:
```ts
interface FindPetsByStatusPathParam {
/**
* Pet id to delete
*/
petId?: number;
[k: string]: unknown;
}
interface FindPetsByStatusQueryParam …
```
> feat: adding new options to `getParametersAsJsonSchema`

- __tests__/operation/get-parameters-as-json-schema.test.ts
- src/operation/get-parameters-as-json-schema.ts
Fixes a bug in the new metadata merging work I did in #617 to not generate an empty `allOf` JSON Schema entry for metadata if there's no metadata on the operation.
See tests.
> fix: don't create an empty metadata allOf is there's no metadata

- __tests__/__datasets__/server-variables.json
- __tests__/index.test.ts
- src/index.ts
| 🚥 Fix RM-3921 |
| :-- |
This fixes a bug in our server variable matching work in `Oas.findOperation()` where if an OAS had a fully variable hostname like `{protocol}://{hostname}/api/public/v1` we wouldn't be able to match against it if that `hostname` was being populated with either a subdomain or a port.
For example, this `servers` config:
```js
"servers": [
{
"url": "{protocol}://{hostname}/api/public/v1",
"variables": {
"protocol": { "default": "http" },
"hostname": { "default": "localhost:10000" }
}
}
]
```
Attempting to find an operation for http://online.example.global:3001/api/public/v1/tables/c445a575-ee58-4aa7/rows/5ba96283-29c2-47f7 within this spec would fail because `online.example.global:3001` wasn't being seen as a valid `hostname`.
Check out the test I wrote or kick off …
> fix: issue where hostname server variables wouldn't match subdomains or ports

- __tests__/operation.test.ts
- src/operation.ts
Updates `Operation.hasOperationId()` to return `false` if an `operationId` is present but an empty string.
> fix: `operation.hasOperationId` should return false for an empty string

- __tests__/operation.test.ts
- src/operation.ts
This modifies the `camelCase` option I introduced on `Operation.getOperationId()` in #602 to clean up operationIds if they're present. I plan on using this work within `api` to always make an attempt to generate friendlier operation accessors.
Since this work was just recently in [17.8.1](https://github.com/readmeio/oas/releases/tag/17.8.1) and we aren't using this new `camelCase` option anywhere I'm not going to bother with a breaking change release on this one.
See tests but this'll transform a non-functional JS accessor operationId like `find/petsByStatus` into the friendlier `findPetsByStatus`.
> feat: `camelCase` opt on `getOperationId()` should clean IDs if present

- __tests__/operation.test.ts
- src/operation.ts
This updates our `Operation.getSecurity()` handling to now return an empty array if `#/components/securitySchemes` is present but is an empty object.
See PR 6389 in ReadMe for background.
See tests.
> fix: `operation.getSecurity()` should return an empty array for an empty `securitySchemes` object

- __tests__/operation.test.ts
- package-lock.json
- package.json
- src/operation.ts
This resolves an issue I discovered while working on https://github.com/readmeio/api/pull/422 where if you called `operation.prepareSecurity()` and then ran OAS validation against the spec you ingested into `oas` validation would fail because `operation.prepareSecurity()` would append our internal security scheme name tracking information to a `_key` property.
Tests never caught this because they were asserting directly against the corrupted spec data. 🙃
> fix: issue where a securityScheme may be corrupted with internal library data

- __tests__/index.test.ts
- src/index.ts
This adds error handling from fully malformed paths that we can't repair to the `Oas.findOperation()` method.
> fix: improved error handling on `Oas.findOperation()` calls

- __tests__/operation/__snapshots__/get-response-as-json-schema.test.ts.snap
- __tests__/operation/get-response-as-json-schema.test.ts
- src/lib/clone-object.ts
- src/lib/openapi-to-json-schema.ts
- src/operation/get-parameters-as-json-schema.ts
- src/operation/get-response-as-json-schema.ts
This updates our response JSON Schema generation to start emitting `$schema` versioning identifiers, something we already do for parameters and request bodies.
Adding this should help to resolve a performance issue I've found in some code generation work I'm doing over in https://github.com/readmeio/api.
> feat: adding $schema version identifiers into generated response JSON Schema

- __tests__/operation/get-response-as-json-schema.test.ts
- src/operation/get-response-as-json-schema.ts
This resolves a data corruption bug I discovered in https://github.com/readmeio/api where if you compile the JSON Schema for an operation response with `getResponseAsJsonSchema`, and somewhere within that response is an `example` property, we'd update the original API definition object that was supplied to `Oas` with the `examples` syntax that `getResponseAsJsonSchema` reshapes `example` to -- rendering the original API definition in a non-spec validating state.
I added a test that runs `getResponseAsJsonSchema` against a response in our own spec and then queries the original spec inside the original `Oas` instance to ensure that the schema property where `example` was present is only set to `examples` in the generated JSON Schema.
:upsidedown-cowboy-quadboy:
> fix: issue where response schemas in the original spec may get overridden

- __tests__/__datasets__/responses.json
- __tests__/operation/__snapshots__/get-response-as-json-schema.test.ts.snap
- __tests__/operation/get-response-as-json-schema.test.ts
- src/lib/clone-object.ts
| 🚥 Fix RM-4226 |
| :-- |
This fixes a crash I introduced in work I did in #634 where if a response does not have a schema we were still attempting to clone it with `JSON.parse(JSON.stringify())`, which fails:
```
> JSON.parse(JSON.stringify(undefined))
VM226:1 Uncaught SyntaxError: Unexpected token u in JSON at position 0
at JSON.parse (<anonymous>)
at <anonymous>:1:6
```
> fix: don't attempt to clone undefined objects, resulting in a crash

- __tests__/__datasets__/response-enums.json
- __tests__/operation/get-response-as-json-schema.test.ts
- package-lock.json
- src/lib/openapi-to-json-schema.ts
- src/operation/get-response-as-json-schema.ts
| 🚥 Fix RM-988 |
| :-- |
This updates our `Operation.getResponseAsJsonSchema()` accessor to auto-add a list of enums into generated descriptions if enums are present.
This is how it'll look in the real world:
See the test and example dataset I added.
> feat: updating response JSON Schema generation to auto-add enums to descriptions

- __tests__/index.test.ts
- src/index.ts
- src/lib/find-schema-definition.ts
| 🚥 Fix RM-4348 |
| :-- |
This updates our `getPaths` accessor to be aware of `$ref` pointers.
See tests.
> feat: adding $ref awareness to `Oas.getPaths()`

- __tests__/operation.test.ts
- src/operation.ts
This fixes a problem in `api` (https://github.com/readmeio/api/issues/488) where if you have an OAS with an `operationId` that has an underscore, like `ExchangeRESTAPI_GetAccounts`, when we call `getOperationId({ camelCase: true })` we were transforming it into `ExchangeRESTAPIGetAccounts` because we didn't recognize an underscore as being a valid character in a potential JS method accessor.
> fix: don't remove underscores in operationIds

- __tests__/operation.test.ts
- src/operation.ts
| 🚥 Fix RM-4919|
| :-- |
This fixes a bug in our `Operation.getHeaders()` method where if an operation had OAuth2 security set up, calling `getHeaders()` on it wouldn't return `Authorization` as a valid header for the operation.
This bug is/was causing issues stream in log viewing where if you attempt to view a log for an operation that has OAuth2 security configured we'd strip the `Authorization` header out because it was unrecognized.
See tests.
> fix: bug in `getHeaders` where it wouldn't return `Authorization` if security was oauth2

- README.md
| 🚥 Fix RM-XXX |
| :-- |
I believe it would be good to show what other commands the tool has besides the `init` command. I think that section is still important, and I've seen other tools show `help` output in their READMEs. This is a shot at doing the same for this tool 🙇 
Visual verification of newly rendered Markdown should be sufficient.
> docs: add commands section to README

- __tests__/__snapshots__/operation.test.ts.snap
- __tests__/lib/openapi-to-json-schema.test.ts
- __tests__/operation.test.ts
- __tests__/operation/get-parameters-as-json-schema.test.ts
- __tests__/operation/get-response-as-json-schema.test.ts
- __tests__/ts-quirks.test.js
- package-lock.json
- package.json
- src/lib/openapi-to-json-schema.ts
- src/operation.ts
- src/operation/get-parameters-as-json-schema.ts
- src/operation/get-response-as-json-schema.ts
| 🚥 Fix https://github.com/readmeio/api/issues/523 |
| :-- |
I've discovered [api](https://github.com/readmeio/api) that if a JSON Schema `title` starts with a number, [json-schema-to-typescript](https://npm.im/json-schema-to-typescript) will leave it in, resulting in a generated Typescript interface that's invalid -- causing `api` SDK generation to crash. Instead of adding in more bespoke logic into this library to fix this very `api`-specific issue I've decided instead to add a new `transform` option to `operation.getParametersAsJsonSchema()` and `operation.getResponseAsJsonSchema()` so I can fix it in `api`.
This new `transform` option takes a single `SchemaObject` object and expects you to return the same. With this I'll be able to do something in `api` to make these problematic …
> feat: addition of a new JSON Schema transformer option + operationId fixes

- __tests__/operation/get-parameters-as-json-schema.test.ts
- __tests__/operation/get-response-as-json-schema.test.ts
- src/operation/get-parameters-as-json-schema.ts
- src/operation/get-response-as-json-schema.ts
This extends the `transformer` option I introduced in #695 to allow the ability to transform a schema object into a pure primitive.
I'm using this over in [api](https://npm.im/api) for transforming schemas that contain a `x-readme-ref-name` property into being the value of that ref.
> feat: supporting transforming a schema object to a primitive

- __tests__/__datasets__/ably.json
- __tests__/operation/get-parameters-as-json-schema.test.ts
- __tests__/operation/get-response-as-json-schema.test.ts
- src/lib/openapi-to-json-schema.ts
- src/operation.ts
- src/operation/get-parameters-as-json-schema.ts
- src/operation/get-response-as-json-schema.ts
This fixes some quirks with the `transformer` option I introduced for compiling JSON Schema where because we're counting `$ref` pointers from `discriminator.mapping` objects, we'd attempt to set an object to a potentially transformed string.
🤡 
I've refactored the `refLogger` system to differentiate between what's a circular `$ref` and what's a discriminator mapping and then introduced a new option to disable emitting discriminator components alongside discriminators -- because I don't need this in [api](https://npm.api).
> fix: quirks with discriminators and the `transformer` JSON Schema option

- __tests__/index.test.ts
- __tests__/operation.test.ts
- src/index.ts
- src/operation.ts
- src/operation/get-parameters-as-json-schema.ts
* This whole `transformer` thing is becoming a real pain and as I only added it for `api` I may end up removing it and looking for an alternative solution there for the problem I'm trying to solve with it.
> fix: various compatibility issues with `api` codegen

- __tests__/operation.test.ts
- src/operation.ts
This fixes an edgase where if a path is `/candidate/{candidate_id}/` and there's no `operationId` we were generating  `getCandidateCandidate_id-`. Normally we lop off starting and trailing `-` but because the path ends in `}/` that's getting converted into `--` and we're only lopping off one of those.
> fix: edgecase where we wouldn't always create valid operationIds

- __tests__/__datasets__/callbacks.json
- __tests__/operation.test.ts
- src/operation.ts
This reverses the logic order for how we extract a `summary` and `description` out of an operation or callback operation when common `summary` and `description` properties are present. Previous we would always prefer the common one over the more specific, but we're reversing this as it makes more sense to do so.
Unfortunately the spec doesn't specify this behavior so we're kind of winging this on how it *feels*.
> fix: reversing the logic order for common summary+descriptions

- __tests__/__snapshots__/operation.test.ts.snap
- __tests__/operation.test.ts
- __tests__/operation/__snapshots__/get-parameters-as-json-schema.test.ts.snap
- __tests__/operation/get-parameters-as-json-schema.test.ts
- src/operation.ts
- src/operation/get-parameters-as-json-schema.ts
| 🚥 Fixes ISSUE_ID |
buddy PR to [#8316](https://github.com/readmeio/readme/pull/8316)
We say [we support this](https://docs.readme.com/main/docs/openapi-compatibility-chart#request-body-object) (and technically we do, it's in the oas/operation correctly) but weren't actually doing anything with that information 
This surfaces request body descriptions out with the json schema so we can display them on the front end
Check the tests - a few older tests should now be passing through description as intended
> feat: pass through requestBody descriptions

- __tests__/operation/get-parameters-as-json-schema.test.ts
- src/operation/get-parameters-as-json-schema.ts
This fixes a pretty large performance issue in `Operation.getParametersAsJSONSchema()` where if an API Definition has a very large schema in a component we will bog down pretty hard converting it to JSON Schema even if we don't need to.
For example this excerpted component schema:
Because these `$ref` pointers, and the parental schema itself, are normally able to be safely dereferenced, we're still adding the into the generated JSON Schema for that parameter or request body that we're generating JSON Schema for on the off chance that they might be used within our API Explorer for schemas that may be circular and we're able to safely render them there.
The problem though is that we're doing this work for everything and everybody. Even if your entire API definition has no circular `$ref` …
> fix: only adding components to generated JSON Schema if we need to

- __tests__/lib/reducer.test.ts
- src/lib/reducer.ts
| 🚥 Fixes  #678  |
Modified reducer to keep matching paths, tags, and/or methods regardless of casing.
Changed casing in existing tests to ensure changes work.
> feat: add case insensitivity for reducer

- __tests__/__datasets__/3-1-primitive-components.json
- __tests__/index.test.ts
- src/index.ts
- src/lib/helpers.ts
- src/lib/openapi-to-json-schema.ts
- src/operation/get-parameters-as-json-schema.ts
- src/operation/get-response-as-json-schema.ts
This fixes a bug in `Oas.dereference()` where if an OpenAPI 3.1 definition with a primitive component schema is present the dereferencing will crash.
> fix: bug where primitive schemas would crash dereferencing

- __tests__/__datasets__/petstore-ref-quirks.json
- __tests__/lib/reducer.test.ts
- src/lib/reducer.ts
@andrew-rdme was seeing the following error when attempting to reduce a file:
```
$ref.substring is not a function
```
which is coming from this line:
https://github.com/readmeio/oas/blob/6162c8445a2dd2727944105ff76d4b2f39360be5/src/lib/reducer.ts#L33
This is happening because of an edge case where a spec file might have an object definition with a property called `$ref`. In other words, say the object were to look something like this:
```json
{
"hello": "world",
"$ref": "example"
}
```
then its schema definition would look something like:
```json
{
"type": "object",
"properties": {
"hello": {
"type": "string",
"description": "A property called `hello`"
},
"$ref": {
"type": "string",
"description": "A property called $ref to see what happens"
}
}
}
```
The reducer was looking blindly for …
> fix(reducer): make sure `$ref`s are actual pointers

- __tests__/operation/__snapshots__/get-parameters-as-json-schema.test.ts.snap
- __tests__/operation/get-parameters-as-json-schema.test.ts
- src/lib/openapi-to-json-schema.ts
| 🚥 Fixes CX-141 |
This adds handling for a quirk within [json-schema-merge-allof](https://npm.im/json-schema-merge-allof) where it cannot merge `enum` arrays like the following:
```js
allOf: [
{
type: 'string',
enum: ['one', 'two', 'three'],
},
{
type: 'string',
enum: ['four', 'five', 'six'],
},
],
```
The error that that library throws, that we catch and then delete the `allOf` from the schema, is this:
Because enums are a known datatype and `json-schema-merge-allof` has support for custom resolvers we can easily handle this merging ourselves resulting in a merged schema of the following:
```js
{
"type": "string",
"enum": ["one", "two", "three", "four", "five", "six"]
}
```
With a spec with one of these `allOf`s this is what this fix looks like before and after: …
> fix: inability to merge enums within an `allOf`

- __tests__/lib/openapi-to-json-schema.test.ts
- package-lock.json
- package.json
- src/lib/openapi-to-json-schema.ts
| 🚥 Fixes RM-4713, RM-4328, CX-68, RM-1814 |
* If `null` is one of these options then it's removed from the `type` array and `nullable: true` is added to the other available options.
> feat: improved support for mixed types and `nullable`

- CHANGELOG.md
- __tests__/lib/openapi-to-json-schema.test.ts
- package-lock.json
- package.json
- src/lib/helpers.ts
- src/lib/openapi-to-json-schema.ts
- src/samples/index.ts
> feat: additional tweaks to json schema generation

- __tests__/lib/openapi-to-json-schema.test.ts
- src/lib/openapi-to-json-schema.ts
Because booleans are a non-compatible schema with strings and numbers if we have a mixed JSON Schema type like `[string, boolean]` we'll now split them into their individual `oneOf` schemas like we do already with `array` and `object`.
> feat: split mixed json schema types with booleans out into a oneOf

- __tests__/__datasets__/callbacks-weird-summary-description.json
- __tests__/operation.test.ts
- src/operation.ts
| 🚥 Fixes ISSUE_ID |
Do tests pass?
> fix: ensure summaries + descriptions are strings

- __tests__/samples/index.test.ts
- src/samples/index.ts
| 🚥 Fixes CX-339 |
This fixes a bug in our response sample generation where if a schema were an `anyOf` that contained a `null` item or was a `type: [...]` schema then the same that we'd generate for that schema property would the error message of "Unknown type: <something>". For example:
> fix: sample generation for mixed null schemas

- __tests__/__datasets__/readonly-writeonly.json
- __tests__/operation/get-parameters-as-json-schema.test.ts
- src/lib/openapi-to-json-schema.ts
- src/operation.ts
- src/operation/get-parameters-as-json-schema.ts
- src/operation/get-response-as-json-schema.ts
We've got a fun quirk in our API Explorer where if you have a `requestBody` that just happens to have a schema full of entirely `readOnly` properties we end up rendering a blank form like this:
Reason this is happening is because the form itself does its own "is this a readOnly schema? then dont render anything" and there's no way for the form to know if a schema is **completely** readOnly until it's its shell (which you see in that screenshot).
The work I've done here is to add two new options to `Operation.getParametersAsJSONSchema()`, `hideReadOnlyProperties` and `hideWriteOnlyProperties`, that will allow us to completely hide these unwanted schemas from our generated JSON Schema object -- which also gives us the flexibility to completely eliminate a `requestBody` schema from being …
> feat: addition of new JSON Schema generation options for hiding r/o schemas

- __tests__/lib/openapi-to-json-schema.test.ts
- __tests__/operation/__snapshots__/get-parameters-as-json-schema.test.ts.snap
- __tests__/operation/get-parameters-as-json-schema.test.ts
- src/lib/openapi-to-json-schema.ts
| 🚥 Fixes RM-7104 |
Currently, we don't surface what the default value is for an enum anywhere so users won't know if there is a default available or not aside from the default form state. This change adds the default value to the schema description so users can tell what the description is.
> feat: surface what the default value is for an enum 

- __tests__/__fixtures__/json-schema.ts
- __tests__/lib/openapi-to-json-schema/__snapshots__/required.test.ts.snap
- __tests__/lib/openapi-to-json-schema/default.test.ts
- __tests__/lib/openapi-to-json-schema/required.test.ts
- src/lib/openapi-to-json-schema.ts
| 🚥 Resolves RM-7587 |
JSON Schema does not have any support for `required: <boolean>` but because some of our users do this, and it does not throw OpenAPI validation because of some extremely loose typings around `schema` in the official JSON Schema definitions that the OAI offers[^1], we're opting to support these users and upgrade their invalid `required` definitions into ones that our tooling can interpret.
[^1]: https://github.com/OAI/OpenAPI-Specification/blob/main/schemas/v3.1/schema.json#L1114-L1121
> feat(jsonschema): adding support for invalid `required: true` properties

- __tests__/__datasets__/security-root-level.json
- __tests__/lib/reducer.test.ts
- src/lib/reducer.ts
| 🚥 Resolves https://github.com/readmeio/rdme/issues/860 |
If you use the reducer with an API definition that has a root-level `security` configuration we wouldn't retain the `securityScheme` components for those resulting in an invalid OpenAPI definition.
> fix(reducer): retain root-defined security definitions

- __tests__/operation/get-response-examples.test.ts
- src/operation/get-response-examples.ts
Hey 👋  I was using the library and noticed that the `getResponseExamples()` declares to use incorrect type. The returned data is not in the shape the type definition claims.
The function casts the returned type incorrectly in [L68](https://github.com/readmeio/oas/blob/main/src/operation/get-response-examples.ts#L68). The used type is shaped like
```ts
type ResponseExamples = {
mediaTypes: Record<string, RMOAS.MediaTypeObject>;
status: string;
}[];
```
but the code actually transforms it into type shaped like
```ts
interface MediaTypeExample {
description?: string;
summary?: string;
title?: string;
value: unknown;
}
```
The actually used type is defined in [L28](https://github.com/mskri/oas/blob/main/src/operation/get-response-examples.ts#L28) which is then returned from the …
> fix: get response example return type

- package-lock.json
- package.json
- tsconfig.json
- tsup.config.ts
| 🚥 Resolves #774 | 
- Added support for cjs and esm with tsup
- Upgraded the node version from 14 to 16 because of the used eslint version, node 14 cant be supported (eslint-typescript use ??= syntax).
Check the output for cjs and esm
> feat: added support for cjs and esm

- __tests__/lib/openapi-to-json-schema.test.ts
- src/lib/openapi-to-json-schema.ts
| 🚥 Resolves #794 |
Only add numeric bounds for numeric types
> fix: only add number bounds to number types

- package.json
When using the latest version of `oas` in https://github.com/readmeio/rdme/pull/856, I'm seeing the following TypeScript errors:
This is happening because `tsup` generates two different type declaration files (one for CJS and one for ESM) that have slight differences...
<details>
<summary>Declaration files screenshot</summary>
</details>
... but the problem is that our `package.json` `exports` field only references the CJS type declaration files:
https://github.com/readmeio/oas/blob/fcc0ec457cc2a823629ac9d0e4b82e4a0a63368c/package.json#L10
Per [the TypeScript docs](https://www.typescriptlang.org/docs/handbook/esm-node.html#packagejson-exports-imports-and-self-referencing:~:text=Attempting%20to%20use%20a%20single%20.d.ts%20file%20to%20type%20both%20an%20ES%20module%20entrypoint%20and%20a%20 …
> fix: get exports working in TS `nodeNext`

- __tests__/index.test.ts
- __tests__/operation.test.ts
- src/index.ts
- src/operation.ts
- src/utils.ts
> fix: get default export working in both ESM/CJS (again)

- .github/workflows/ci.yml
- package-lock.json
- package.json
- tsconfig.json
With the latest `oas-normalize` and `@readme/eslint-config` updates in #802, this library now requires Node 18.
> feat(breaking): drop node 16 support

- .github/workflows/ci.yml
- packages/oas-extensions/package.json
- packages/oas-normalize/package.json
- packages/oas-to-har/package.json
- packages/oas/package.json
Removed the `pretest` scripts so we're not doubly linting/building and swapped out the hand-defined `build` order for lerna, which seemingly takes care of it perfectly :buzzfeed-wow:
Does everything still pass? I confirmed it does locally!
> refactor: build cleanup

- package-lock.json
- package.json
- packages/oas-extensions/package.json
- packages/oas-extensions/tsconfig.json
- packages/oas-extensions/tsup.config.ts
- packages/oas-normalize/.eslintrc
- packages/oas-normalize/package.json
- packages/oas-normalize/src/.sink.d.ts
- packages/oas-normalize/tsconfig.json
- packages/oas-normalize/tsup.config.ts
- packages/oas-to-har/package.json
- packages/oas-to-har/tsconfig.json
- packages/oas-to-har/tsup.config.ts
- packages/oas/package.json
- packages/oas/src/lib/helpers.ts
- packages/oas/src/operation/get-response-as-json-schema.ts
- packages/oas/tsconfig.json
- packages/oas/tsup.config.ts
- tsconfig.base.json
- tsup.config.ts
Consolidates our many TS and `tsup` configs across these new packages.
I've also added a root `attw` script that we can run to run [attw](https://arethetypeswrong.github.io/) across every package.
> refactor: consolidating our ts and tsup configs

- packages/oas-to-har/src/index.ts
- packages/oas/src/index.ts
- packages/oas/src/operation.ts
- packages/oas/src/utils.ts
- packages/oas/test/index.test.ts
- packages/oas/test/utils.test.ts
Doing `export default { .. }` and then loading a specific utility as `import { ... } from 'oas/utils'` gets weird with `tsup`, and it thinks that our utilities don't exist there, so I'm refactoring `oas/utils` to no longer have a default export.
> fix(oas): slightly refactoring how our utilities are exported

- .github/workflows/ci.yml
- .prettierignore
- package.json
- packages/oas-extensions/.eslintignore
- packages/oas-extensions/.npmignore
- packages/oas-extensions/package.json
- packages/oas-normalize/.eslintignore
- packages/oas-normalize/.npmignore
- packages/oas-normalize/package.json
- packages/oas-to-har/.eslintignore
- packages/oas-to-har/.npmignore
- packages/oas-to-har/package.json
- packages/oas/.eslintignore
- packages/oas/.npmignore
- packages/oas/package.json
Doing a little mess-around in this repo and refactored a few config files (some are a bit new and opinionated so feel free to push back on any of this)
To confirm the `npmignore` changes, you can confirm this by running `npm pack` and looking at the file list in any of the subpackages. And if the linting step passes, the Prettier/ESLint config file changes should be safe.
> refactor: random config file cleanup

- package-lock.json
- packages/oas-extensions/package.json
Something I didn't know is that with Lerna if you use the `file:../<dirname>` syntax for loading dependencies in a monorepo, but do that for a peer dependency, Lerna and NPM won't change that `file:` reference when publishing a release. This was causing issues within `oas-extensions` where because `oas` was listed as a peer dependency when I loaded in the latest release of `oas-extensions` it was trying to load `oas` from the same `file:` path in another repository of mine. 
Yikes!
> fix(oas-extensions): moving `oas` from being a peer to a hard dep

- package-lock.json
- packages/oas-to-har/package.json
- packages/oas-to-har/src/index.ts
- packages/oas-to-har/src/lib/utils.ts
| 🚥 Resolves #815 |
This slightly reduces our `lodash` footprint in `oas-to-har` by loading the dedicated packages for `lodash.get` and `lodash.set` instead of grabbing those methods out of the larger package.
#815 also was curious about removing `qs` in favor of `URLSearchParams` because `URLSearchParams` doesn't support deep objects the same way `qs` does.
> feat(oas-to-har): reducing the `lodash` footprint

- package-lock.json
- packages/oas/src/index.ts
- packages/oas/test/index.test.ts
I've updated the `.getTags()` function to be able to handle webhooks as well in preparation for our webhooks support. This makes it so that any webhooks present in the file will have their tags correctly generated and put in the correct category. Prior to this, it was just placing the endpoint pages in random places. 
This particular test will fail until the [updated](https://github.com/readmeio/oas-examples/pull/90) `webhooks.yaml` file on the `oas-examples` repo is pulled in.
> refactor: update getTags() function to handle webhooks

- packages/oas/src/index.ts
- packages/oas/test/__datasets__/ordered-tags.json
- packages/oas/test/index.test.ts
| 🚥 Resolves CX-514 |
These changes adds support for ordering pages by the `tags` array as defined in OAS spec.
Per [OAS Spec](https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.0.0.md#fixed-fields):
`The order of the tags can be used to reflect on their order by the parsing tools.`
The tags on `this.api.tags` comes in in the correct order, however, we create a new array `Array.from(allTags)` with tags added as we parse the file from top down. With these changes, I sort this array against the correctly ordered `oasTags`. Since the sorting will put tags that exist only at the endpoint level to the front, I also separate them and tack them on to the end of the sorted tags.
> feat: add support for ordering via `tags` array

- package-lock.json
- packages/oas-to-har/package.json
- packages/oas-to-har/src/index.ts
- packages/oas-to-har/src/lib/utils.ts
| 🚥 Resolves(?) https://github.com/readmeio/oas/security/dependabot/14 |
Swaps out our `lodash.get` and `lodash.set` packages for the more modern ES equivalents to hopefully take care of https://github.com/readmeio/oas/security/dependabot/14
Do tests pass?
> chore(deps): lodash security vuln

- packages/oas-normalize/src/index.ts
- packages/oas/README.md
- packages/oas/src/operation/index.ts
Deprecating the `operation.getExtension()` method so end users know what they should be using instead.
Also when pairing with @mjcuva on Friday I noticed that the `OASNormalize.version()` method has pretty shoddy types so fixed those up too.
Mostly doc updates, only QA is copy-editing really!
> docs: deprecate `operation.getExtension()`, typing improvements 

- packages/oas/src/extensions.ts
Adds a type definition + docs for our new `correspondingExample`.
> feat(extensions/code-samples): add support for correspondingExample

- package-lock.json
- packages/oas-to-snippet/README.md
- packages/oas-to-snippet/package.json
- packages/oas-to-snippet/src/index.ts
- packages/oas-to-snippet/test/index.test.ts
@kanadgupta has been running into some trouble this week trying to upgrade our `oas-to-snippet` integration in our API Explorer to comply with its new asynchronous nature. Instead of trying to refactor the internals of [formdata-to-string](https://npm.im/formdata-to-string), which is requiring [httpsnippet](https://npm.im/@readme/httpsnippet) to be async, I ended up figuring out a way to remove `formdata-to-string` entirely. 
https://github.com/readmeio/httpsnippet/pull/224
With that work `oas-to-snippet` can be a synchronous library again.
This will be a breaking change to `oas-to-snippet`.
> feat(snippet): making the library synchronous again

- packages/oas-to-snippet/package.json
- packages/oas-to-snippet/src/index.ts
- packages/oas-to-snippet/src/types.ts
- packages/oas-to-snippet/tsup.config.ts
This re-exports the `HarRequest` type out of `@readme/httpsnippet` from `oas-to-har` so it can be easily used from that instead of having to re-import, and have `@readme/httpsnippet` as a dependency, when you need it.
> feat(oas-to-snippet): exporting the `HarRequest` type for use

- packages/oas-normalize/src/index.ts
- packages/oas-normalize/src/lib/utils.ts
- packages/oas-normalize/tsconfig.json
- packages/oas-to-har/src/index.ts
- packages/oas-to-har/src/lib/configure-security.ts
- packages/oas-to-har/src/lib/style-formatting/index.ts
- packages/oas-to-har/src/lib/style-formatting/style-serializer.ts
- packages/oas-to-har/src/lib/utils.ts
- packages/oas-to-har/tsconfig.json
- packages/oas-to-snippet/src/index.ts
- packages/oas-to-snippet/src/languages.ts
- packages/oas-to-snippet/tsconfig.json
- Enabled strict mode in `oas-normalize`, `oas-to-har`, and `oas-to-snippet`
- Added more specific types across the board in `oas-normalize`. It's always bugged me that `.validate()` returns a `Promise<any>`.
Mostly stricter types, no real functional changes (except maybe slightly better error handling in certain cases).
> refactor: strict mode, more helpful return types

- package-lock.json
- packages/oas-to-har/package.json
- packages/oas-to-har/src/index.ts
- packages/oas-to-har/src/lib/utils.ts
Looks like our CJS codebase doesn't like `lodash-es`:
This PR updates our lodash usage to the standard CJS package instead. If that doesn't solve the problem then I'm gonna look into the far less ideal option, which is including `lodash-es` in our `tsup` bundle, sort of like how we do in [the `api` repo](https://github.com/readmeio/api/blob/429fcf9d9343a52c3cc9fd423f0f8193ac7d17d4/packages/core/tsup.config.ts#L15-L21).
Tests still pass, but when has that ever been an indicator of things working? 🤡
> fix(oas-to-har): use CJS lodash instead

- package-lock.json
- packages/oas-to-har/package.json
- packages/oas-to-har/src/index.ts
- packages/oas-to-har/src/lib/lodash.ts
- packages/oas-to-har/src/lib/utils.ts
- packages/oas-to-snippet/package.json
- packages/oas-to-snippet/src/index.ts
- packages/oas-to-snippet/src/types.ts
**Before**
```
@readme/httpsnippet            9.0.0         9.0.0   10.0.0  node_modules/@readme/httpsnippet     oas-to-snippet@npm:@readme/oas-to-snippet@25.0.1
@types/node                  20.12.5       20.12.7  20.12.7  node_modules/@types/node             oas-to-snippet@npm:@readme/oas-to-snippet@25.0.1
@types/node                  20.12.5       20.12.7  20.12.7  node_modules/@types/node             oas@24.2.1
eslint                        8.57.0        8.57.0    9.0.0  node_modules/eslint                  oas-to-har@npm:@readme/oas-to-har@23.2.4
eslint                        8.57.0        8.57.0    9.0.0  node_modules/eslint                  oas-normalize@11.0.3
eslint                        8.57.0        8.57.0    9.0.0  node_modules/eslint                  oas …
```
> fix: no more lodash, bump types, type cleanup/re-export

- packages/oas-to-snippet/src/index.ts
- packages/oas-to-snippet/test/__snapshots__/index.test.ts.snap
- packages/oas-to-snippet/test/index.test.ts
- packages/oas-to-snippet/test/languages.test.ts
I don't know why I thought this was a good idea but having to manually invoke `getClientInstallationInstructions()` to pull back installation instructions for a client you're generating a snippet for makes absolutely no sense. This modifies the returned object from `oas-to-snippet` to now include an `install` property that includes this data.
> feat(oas-to-snippet): surface installation instructions with snippets

- packages/oas-normalize/src/index.ts
- packages/oas-normalize/test/index.test.ts
- packages/oas-to-har/test/lib/style-formatting/multipart-form-data.test.ts
Discovered this while running our OpenAPI 3.1 webhooks example through `OASNormalize.validate()` but when you supply `convertToLatest` we always attempt to funnel the API definition through `swagger2openapi`; because OpenAPI 3.1 definitions with only webhooks don't have paths `swagger2openapi` throws an error on no `paths` being present.
> fix(oas-normalize): dont attempt to upconvert an OpenAPI definition

- .github/workflows/ci.yml
Node 22 just dropped — adding some funkier syntax so we can dynamically support all the Node releases we want to. Added some comments with links to resources on the subject!
> ci: dynamic args for `actions/setup-node`

- packages/oas/src/samples/index.ts
- packages/oas/test/samples/index.test.ts
This supports OpenAPI "examples" property. This will notably fix all issues with FastAPI generating documentation.
I ran it on multiple documentations with success but I might have missed something. Let me know if I did.
> feat: support examples from openapi 3.1

- packages/oas/src/operation/index.ts
- packages/oas/test/operation/index.test.ts
Talking with @julshotal this afternoon I stumbled upon some oversight with our Git project planning where I wasn't sure what we'd use for endpoint pages we're storing in Git, either alternating between using `title` (when present) or the `camelCase` option on `Operation.getOperationId()`. Long story short working it out with her I discovered a bug in this method where we weren't camelcasing underscores in auto-generated IDs (like `postAc_eq_hazard180` -> `postAcEqHazard180`). Frustratingly enough I had a test that was testing for this very specific thing, the test just wasn't asserting the right expectation.
Additionally while working on a fix for this I'm also proposing another small tweak to this same method to no longer generate operation IDs with consecutive words. This issue is …
> fix(oas): numerous tweaks to our camelCase `operationId` generation

- packages/oas/src/operation/index.ts
- packages/oas/test/operation/index.test.ts
Reverts readmeio/oas#851
This is breaking a lot of tests in our main app and we're afraid that customers are relying on these trash-ass operation IDs we're currently generating.
I'm going to dump this fix behind another opt-in flag on `getOperationId` when I've got time.
> revert: "fix(oas): numerous tweaks to our camelCase `operationId` generation"

- packages/oas/src/operation/lib/get-requestbody-examples.ts
I forgot to clean up some ugly typing that I wrote as part of my work on https://github.com/readmeio/oas/pull/866. This cleans that up
Do tests still pass?
> fix: make `RequestBodyExamples` type stricter

- package-lock.json
- packages/oas/src/operation/lib/get-example-groups.ts
- packages/oas/test/operation/lib/__snapshots__/get-example-groups.test.ts.snap
Fixes a few minuscule bugs with this `exampleGroups` object generation:
This `exampleGroups` object has some wonky ergonomics that I'm already reckoning with but I can't seem to think of an alternative approach that warrants a breaking change. Stay tuned I guess?
Do tests still pass?
> fix(oas/exampleGroups): properly set name for code samples

- package-lock.json
- packages/oas/package.json
| 🚥 Resolves |
Memoize had a vulnerability and was fixed with v0.4.16.
https://github.com/medikoo/memoizee/issues/133
```
┌─────────────────────┬────────────────────────────────────────────────────────┐
│ low                 │ es5-ext vulnerable to Regular Expression Denial of     │
│                     │ Service in `function#copy` and                         │
│                     │ `function#toStringTokens`                              │
├─────────────────────┼────────────────────────────────────────────────────────┤
│ Package             │ es5-ext                                                │
├─────────────────────┼────────────────────────────────────────────────────────┤
│ Vulnerable versions │ >=0.10.0 <0.10.63                                      │ …
```
> fix(oas): update memoizee(vulnerability)

- package-lock.json
- packages/oas-normalize/package.json
- packages/oas/package.json
This bumps `@readme/openapi-parser` to pull in the new schema changes @kanadgupta and @darrenyong did to resolve issues where folks couldn't use `description` in server variables.
> chore(deps): bumping openapi-parser

- packages/oas/src/operation/index.ts
- packages/oas/test/__fixtures__/create-oas.ts
- packages/oas/test/lib/openapi-to-json-schema.test.ts
- packages/oas/test/operation/index.test.ts
- packages/oas/test/operation/lib/get-parameters-as-json-schema.test.ts
- packages/oas/test/operation/lib/get-response-as-json-schema.test.ts
| 🚥 Resolves https://github.com/readmeio/oas/pull/869 |
This resurrects the work I originally did in https://github.com/readmeio/oas/pull/851, but unfortunately had to revert, to create a new `friendlyCase` option on `Operation.getOperationId()` for generating friendlier camelCase operation IDs that we can use in our upcoming Git storage system for API references. 
I reorganized a bunch of the tests for `camelCase` to retain them all along with this new option.
> feat(oas): creation of a new `friendlyCase` option for `.getOperationId()`

- package-lock.json
- packages/postman-types/.eslintrc
- packages/postman-types/LICENSE
- packages/postman-types/README.md
- packages/postman-types/package.json
- packages/postman-types/schemas/v2.0.0.json
- packages/postman-types/schemas/v2.1.0.json
- packages/postman-types/src/index.ts
- packages/postman-types/tsconfig.json
- packages/postman-types/tsup.config.ts
I'd like some TS types on Postman collections for some new work I'm doing with `oas-normalize` so this creates us a new `postman-types` package that, like [openapi-types](https://npm.im/openapi-types), will do just that.
> feat: new library to expose typings for postman collections

- packages/oas/src/lib/get-auth.ts
- packages/oas/test/lib/get-auth.test.ts
Adds bearer auth support for [our `x-default` extension](https://docs.readme.com/main/docs/openapi-extensions#authentication-defaults).
Slack thread for context: https://readmeio.slack.com/archives/C04EF46CU/p1719422826977949
> feat(oas): check for `x-default` for bearer auth

- packages/oas/src/extensions.ts
- packages/oas/src/index.ts
- packages/oas/test/index.test.ts
| 🚥 Resolves [Slack thread](https://readmeio.slack.com/archives/C06DBJRSHJP/p1717788236438779) |
Adds an extension to disable sorting the tag generation by the `tags` array in the OAS file. Instead, it will use the method we used before, which is top-down. 
> feat: add `disable-tag-sorting` extension

- packages/oas/README.md
This just fixes a small typo in the README.
> docs: typo

- packages/oas/src/lib/openapi-to-json-schema.ts
- packages/oas/test/lib/__snapshots__/openapi-to-json-schema.test.ts.snap
- packages/oas/test/lib/openapi-to-json-schema.test.ts
| 🚥 Resolves RM-10218 |
For folks that use custom keywords in their polymorphic objects, we now specify a resolution strategy (i.e., simply select the first value) as opposed to totally ignoring the object.
Do tests pass?
> fix(oas/json schema): add default resolver for unknown keywords

- packages/oas/src/lib/openapi-to-json-schema.ts
- packages/oas/test/lib/openapi-to-json-schema.test.ts
- packages/oas/test/operation/lib/__snapshots__/get-parameters-as-json-schema.test.ts.snap
| 🚥 Resolves CX-947 |
With our new "Defaults to" copy that we're surfacing for request parameters, we now have duplicated info for parameters that are both enums and contain a default value ([bin site preview is here](https://bin.readme.com/s/669ea01aef9101006ed22937)):
This PR removes that description-updating logic from our `openapi-to-json-schema` handling.
Is this the right spot to make this change? This logic is only for request parameters right?
> fix(oas): don't add defaults to enum param descriptions

- packages/oas/README.md
- packages/oas/src/index.ts
- packages/oas/test/__datasets__/circular-path.json
- packages/oas/test/__snapshots__/index.test.ts.snap
- packages/oas/test/index.test.ts
- packages/oas/test/reducer/index.test.ts
This creates a new `.getOperationById()` method on the main `Oas` instance that allows us to retrieve an `Operation` or `Webhook` instance by either the `operationId` that's set to the schema, or if that's missing then the default generated behavior from `Operation.getOperationId()`.
I plan on using this within our main app to retrieve `path` and `method` for an operation based on the data I have for it: just an `operationId`.
The tests I wrote have been sort of ported over from the `Operation.getOperationById()` tests but heavily reduced as I don't need to re-test that thing.
> feat: creation of a new `.getOperationById()` method

- packages/oas/src/operation/index.ts
- packages/oas/src/types.ts
- packages/oas/test/operation/index.test.ts
In our `operation.getSecurityWithTypes()` method, this adds/documents a new property called `_requirements` that contains the required scopes for the operation + security scheme[^1].
I also exported our `SecurityType` type and added a JSDoc for it.
Should be a minor additive change. Do tests/snapshots pass?
[^1]: [read more about the security requirement object here](https://spec.openapis.org/oas/v3.1.0#security-requirement-object)
> feat(operation/getSecurityWithTypes): expose required scopes

- packages/oas/src/index.ts
- packages/oas/test/index.test.ts
Explicitly defines our types for `oas.splitUrl()`.
Before (inferred return types):
After (explicitly defined return types):
Also, strengthens a few test assertions.
> feat(oas): type improvements for `oas.splitUrl()`

- packages/oas/src/index.ts
- packages/oas/src/types.ts
Noticed some type discrepancies in how we describe server variables — this PR fixes that.
Do tests pass?
> refactor(oas): export and reuse `Variables` type

- packages/oas/src/extensions.ts
- packages/oas/src/index.ts
- packages/oas/src/operation/lib/get-example-groups.ts
- packages/oas/test/extensions.test.ts
| 🚥 Partially resolves RM-10641, RM-10720, RM-10730 |
Adds an OAS extension so folks can configure OAuth flows handling. These options are inspired by Swagger UI's configuration options: https://swagger.io/docs/open-source-tools/swagger-ui/usage/oauth2/
In my testing, I've found these ones are necessary for a v1 release of OAuth flows support, but I'm down to add more options further down the line.
Also, a super tiny type-fix with our `CODE_SAMPLES` extension.
Tests appear to pass, but I would **love** targeted feedback on the following million dollar question: **do you feel good about the naming conventions and defaults**? This will be impossible to change in the future so I'd love to make sure we develop a consensus first!
I opted to stick with the Swagger …
> feat(oas/extensions): oauth configuration options

- packages/oas/README.md
- packages/oas/src/operation/index.ts
- packages/oas/test/operation/index.test.ts
| 🚥 Resolves N/A |
I personally find myself checking if the current Operation is a Webhook or not. I looked at the `Operation` class and didn't see anything like this. Thought it'd be useful so we don't have to keep type checking in the main repo. 
I put the check on the Operation class since a Webhook will always be an Operation class but an Operation class might not be a Webhook or Callback class. 
> feat: add Operation.isWebhook()

- package-lock.json
- packages/oas-to-snippet/README.md
- packages/oas-to-snippet/package.json
- packages/oas-to-snippet/src/languages.ts
- packages/oas-to-snippet/test/__snapshots__/index.test.ts.snap
- packages/oas-to-snippet/test/__snapshots__/languages.test.ts.snap
- packages/oas-to-snippet/test/index.test.ts
This bumps `@readme/httpsnippet` in order to pull in some modernizations to our JS and Node snippets. Check out https://github.com/readmeio/httpsnippet/pull/245 for more information on what all that relates to.
> feat(snippet): upgrading `httsnippet` for some JS/Node modernizations

- package-lock.json
- packages/oas-normalize/package.json
- packages/oas-normalize/test/index.test.ts
- packages/oas/package.json
- packages/oas/src/index.ts
- packages/oas/test/index.test.ts
| 🚥 Resolves https://github.com/readmeio/oas/issues/901 |
`path-to-regexp@7` has a vulnerability regarding backtick expressions https://github.com/advisories/GHSA-9wv6-86v2-598j so we need to upgrade it.
* Unfortunately they've changed the the `MatchResult` interface we use to no longer return `index` so this may need to be treated as a breaking change as we have returned that value on `.findOperation()` and `.findOperationWithoutMethod()`.
> chore(deps): upgrading `path-to-regexp`

- packages/oas/src/operation/index.ts
- packages/oas/test/operation/lib/get-requestbody-examples.test.ts
There is a weird case in our main repo where we initialize `Webhooks` with an empty `requestBodyExamples` with the following structure:
```
requestBodyExamples: [
{
mediaType: 'application/json',
examples: [{
value: undefined
}],
},
];
```
This causes `Operation.getRequestBodyExamples()` to return with an empty request example even though we should be creating an example for them. This adds an extra check so that we avoid returning the empty example and proceed to the subsequent `getRequestBodyExamples()` call that generates an example for the user.
> fix: add empty `value` check in getRequestBodyExamples()

- package-lock.json
- packages/oas-normalize/package.json
- packages/oas-to-har/package.json
- packages/oas-to-har/test/index.test.ts
- packages/oas-to-snippet/package.json
- packages/oas/package.json
This repo is a bit weird in that we need to build the dists before running our test suite, so running tests from the subpackages might result in confusing errors. This PR makes it so we have a bit of a nicer error in case of that.
> chore: prevent tests from being run in subpackages

- package-lock.json
- package.json
- packages/oas-normalize/package.json
- packages/oas-normalize/src/index.ts
- packages/oas-normalize/src/lib/utils.ts
- packages/oas-to-har/package.json
- packages/oas-to-har/src/index.ts
- packages/oas-to-har/src/lib/style-formatting/style-serializer.ts
- packages/oas-to-har/src/lib/utils.ts
- packages/oas-to-snippet/package.json
- packages/oas-to-snippet/src/index.ts
- packages/oas-to-snippet/src/languages.ts
- packages/oas-to-snippet/test/__snapshots__/index.test.ts.snap
- packages/oas-to-snippet/test/languages.test.ts
- packages/oas/.eslintrc
- packages/oas/package.json
- packages/oas/src/analyzer/queries/openapi.ts
- packages/oas/src/index.ts
- packages/oas/src/lib/clone-object.ts
- packages/oas/src/lib/openapi-to-json-schema.ts
- packages/oas/src/operation/index.ts
- packages/oas/src/operation/lib/get-mediatype-examples.ts
- packages/oas/src/reducer/index.ts
- packages/oas/src/samples/index.ts
- packages/oas/src/samples/utils.ts
- packages/oas/test/analyzer/queries/openapi.test.ts
- packages/postman-types/src/index.ts
Before:
```
Package                      Current        Wanted  Latest  Location                                        Depended by
@readme/eslint-config         14.0.0        14.1.2  14.1.2  node_modules/@readme/eslint-config              oas
@readme/httpsnippet           10.1.0        10.1.1  11.0.0  node_modules/@readme/httpsnippet                oas-to-snippet@npm:@readme/oas-to-snippet@25.2.20
@readme/oas-examples          5.15.1        5.18.2  5.18.2  node_modules/@readme/oas-examples               oas@25.0.1
@readme/oas-examples          5.15.1        5.18.2  5.18.2  node_modules/@readme/oas-examples               oas-normalize@11.1.2
@readme/oas-examples          5.15.1        5.18.2  5.18.2  node_modules/@readme/oas-examples …
```
> chore(deps): npm up

- packages/oas/src/analyzer/index.ts
- packages/oas/src/analyzer/queries/readme.ts
- packages/oas/src/analyzer/types.ts
- packages/oas/test/analyzer/__snapshots__/index.test.ts.snap
- packages/oas/test/analyzer/queries/readme.test.ts
| 🚥 Resolves RM-11499 |
Add a check to the analyzer if the definition previously had a reference in it. Once we dereference a file we add `x-readme-ref-name` as a way to keep track of the previous name. This surfaces if that extension exists in the definition being analyzed. 
Tests should pass, and analyzer should have a new `x-readme-ref-name` field being returned.
> feat(oas): add ref name to analyzer

- packages/oas/README.md
- packages/oas/src/analyzer/index.ts
- packages/oas/src/analyzer/queries/openapi.ts
- packages/oas/src/analyzer/types.ts
- packages/oas/src/index.ts
- packages/oas/src/lib/openapi-to-json-schema.ts
- packages/oas/src/operation/index.ts
- packages/oas/src/operation/lib/get-mediatype-examples.ts
- packages/oas/src/operation/lib/get-parameters-as-json-schema.ts
- packages/oas/src/operation/lib/get-response-as-json-schema.ts
- packages/oas/src/types.ts
- packages/oas/test/analyzer/__snapshots__/index.test.ts.snap
- packages/oas/test/analyzer/queries/openapi.test.ts
- packages/oas/test/operation/index.test.ts
- packages/oas/test/operation/lib/get-response-as-json-schema.test.ts
This adds support to `oas/analyzer` for surfacing information on if a given API definition utilizes [common parameters](https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.1.0.md#path-item-object).
I've also gone through and updated a bunch of bad deep links to parts of the OAS. Would be nice if the OAI would stop breaking these deep links every couple of years.
> feat(oas): adding support for common parameter detection to the analyzer

- packages/oas/src/reducer/index.ts
- packages/oas/test/reducer/index.test.ts
| 🚥 Resolves https://github.com/readmeio/oas/issues/925 |
This updates `oas/reducer` to account for deep `$ref` pointers like `#/components/examples/event-min/value`. Normally when we're running through components to remove we only look at `#/components/examples/event-min`, however when a schema like this is deeply referenced we won't pick up that it's used and end up removing `event-min` from the components block, resulting in a corrupted schema that will no longer validate.
> fix(oas): account for deep `$ref` pointers when reducing an API def

- packages/oas-normalize/src/index.ts
- packages/oas-normalize/src/lib/utils.ts
- packages/oas-normalize/test/index.test.ts
| 🚥 Resolves https://github.com/readmeio/rdme/issues/1152 |
When we moved `oas-normalize` off `node-fetch` and to native `fetch` we lost the ability to supply basic auth credentials directly in the URL string as `fetch` doesn't support that.
> fix(oas-normalize): support for basic auth in url strings

- knip.ts
- package-lock.json
- package.json
- packages/oas-to-har/src/lib/style-formatting/style-serializer.ts
- packages/parser/package.json
- packages/parser/src/validators/schema.ts
- packages/parser/src/validators/spec.ts
This enables [Knip](https://knip.dev) across the repository and cleans up a couple things that were being exported but unused.
> ci: enabling knip on the repository

- packages/oas-to-snippet/src/index.ts
- packages/oas-to-snippet/test/index.test.ts
as part of the issue in [this thread](https://readmeio.slack.com/archives/C089VLEECKC/p1741034582475949), it feels like unexpected behavior that we show `api` installation instructions when the snippet generation fails and we fallback to `fetch`. this fixes that.
> fix(snippet): hide install instructions for fetch fallback

- package-lock.json
- package.json
- packages/http-status-codes/package.json
- packages/jest-expect-har/package.json
- packages/jest-expect-openapi/package.json
- packages/oas-normalize/package.json
- packages/oas-to-har/package.json
- packages/oas-to-snippet/package.json
- packages/oas/package.json
- packages/parser/package.json
- packages/postman-types/package.json
Node 18 hits EOL at the end of next month and with the upcoming ESM improvements in Node 20+, with which we'll be able to simplify our build processes, we're getting ahead of the gate and dropping Node 18 now.
> feat: dropping support for node 18

- packages/jest-expect-har/package.json
- packages/jest-expect-har/test/tsconfig.json
- packages/jest-expect-har/tsconfig.json
- packages/jest-expect-har/tsup.config.ts
This updates `jest-expect-har` to support CJS and ESM dists, as well as consolidating its various TS configs to use the core one in this repository.
> feat(jest-expect-har): support for CJS and ESM builds

- packages/jest-expect-openapi/package.json
- packages/jest-expect-openapi/src/index.ts
- packages/jest-expect-openapi/test/index.test.ts
- packages/jest-expect-openapi/test/tsconfig.json
- packages/jest-expect-openapi/tsconfig.json
- packages/jest-expect-openapi/tsup.config.ts
Like in https://github.com/readmeio/oas/pull/958 this updates `jest-expect-openapi` to support CJS and ESM dists, as well as consolidating its various TS configs to use the core one in this repository.
> feat(jest-expect-openapi): support for CJS and ESM builds

- package-lock.json
- packages/oas-to-snippet/package.json
- packages/oas-to-snippet/test/__fixtures__/plugin.ts
- packages/oas-to-snippet/test/__fixtures__/pluginFailure.ts
- packages/oas-to-snippet/test/__snapshots__/index.test.ts.snap
- packages/oas-to-snippet/test/index.test.ts
- packages/oas-to-snippet/test/languages.test.ts
Both `oas-to-snippet` and [httpsnippet-client-api](https://npm.im/httpsnippet-client-api) depending on `oas` has always made it difficult to do breaking releases of `oas` because after publishing `oas`, which automatically bumps `oas-to-snippet`, I then need to bump `httpsnippet-client-api` and _then_ pull that back into `oas-to-snippet`.
Nuts to all that. Since we are only loading it in tests to test out behavior for [api](https://npm.im/api) code snippets we can instead just mock out plugin examples and test around that.
> chore(oas-to-snippet): mock out `httpsnippet-client-api` behaviors

- package-lock.json
- packages/oas/test/analyzer/queries/openapi.test.ts
- packages/oas/test/index.test.ts
- packages/parser/package.json
- packages/parser/test/specs/circular-slowdowns/circular-slowdowns.test.ts
- packages/parser/test/specs/circular-slowdowns/schema.json
We uncovered a problem with the dereferencing functionality within our OpenAPI parser on schemas with an extensive amount of circular references where under these circumstances it could take upwards to an hour to dereference a schema. I was able to trace it down to being a problem within [@apidevtools/json-schema-ref-parser](https://npm.im/@apidevtools/json-schema-ref-parser) where because it was not always using its internal cache it would get into situations where, when parsing a circular reference, it would often attempt to re-parse that same reference multiple times.
I submitted a fix for this over in https://github.com/APIDevTools/json-schema-ref-parser/pull/380, and this pulls that in along with builds a unit test around one of these problematic schemas.
> fix(parser): internal cache improvements to dereferencing circular refs

- package-lock.json
- package.json
- packages/oas-normalize/src/index.ts
- packages/oas/src/analyzer/index.ts
- packages/oas/src/index.ts
- packages/oas/src/lib/get-auth.ts
- packages/oas/src/lib/get-user-variable.ts
- packages/oas/src/lib/openapi-to-json-schema.ts
- packages/oas/src/operation/index.ts
- packages/oas/src/operation/lib/dedupe-common-parameters.ts
- packages/oas/src/operation/lib/get-callback-examples.ts
- packages/oas/src/operation/lib/get-example-groups.ts
- packages/oas/src/operation/lib/get-mediatype-examples.ts
- packages/oas/src/operation/lib/get-requestbody-examples.ts
- packages/oas/src/operation/lib/get-response-examples.ts
- packages/oas/src/samples/index.ts
- packages/oas/src/samples/utils.ts
- packages/oas/test/.eslintrc
- packages/oas/test/__fixtures__/create-oas.ts
- packages/oas/test/analyzer/queries/openapi.test.ts
- packages/oas/test/analyzer/queries/readme.test.ts
- packages/oas/test/extensions.test.ts
- packages/oas/test/index.test.ts
- packages/oas/test/operation/index.test.ts
- packages/oas/test/operation/lib/get-response-examples.test.ts
- packages/oas/test/samples/index.test.ts
We have a new custom ESLint rule [readme/no-wildcard-imports](https://github.com/readmeio/standards/blob/main/packages/eslint-plugin/docs/rules/no-wildcard-imports.md) for banning `import * as something from 'module'` as we've been having issues with tree shaking in some old libraries. This updates our shared ESLint config and implements this rule across every package here.
> refactor: removing wildcard imports

- packages/oas/README.md
- packages/oas/src/analyzer/index.ts
- packages/oas/src/analyzer/queries/openapi.ts
- packages/oas/src/analyzer/types.ts
- packages/oas/test/analyzer/__snapshots__/index.test.ts.snap
- packages/oas/test/analyzer/queries/openapi.test.ts
This pull request enhances the OpenAPI analyzer by adding functionality to calculate and report the raw and dereferenced file sizes of an API definition.
* Added support for calculating the size of the raw OpenAPI file (`rawFileSize`) and the dereferenced OpenAPI file (`dereferencedFileSize`) in MB. These values are now included in the general analysis results. 
* Updated the `README.md` to include descriptions of the new `rawFileSize` and `dereferencedFileSize` metrics in the analyzer output.
* Added snapshot tests to validate the inclusion of `rawFileSize` and `dereferencedFileSize` in the analyzer output. 
* Introduced unit tests for `fileSize` and `fileSizeDereferenced` to verify their correctness.
> feat(oas): add support for displaying definition size in analyzer

- .vscode/settings.json
- packages/oas-examples/test/.eslintrc
- packages/oas-examples/test/index.test.ts
- packages/oas/src/analyzer/index.ts
- packages/oas/src/analyzer/queries/openapi.ts
- packages/oas/src/analyzer/types.ts
- packages/oas/test/__datasets__/responses.json
- packages/oas/test/analyzer/__snapshots__/index.test.ts.snap
- packages/oas/test/analyzer/index.test.ts
- packages/oas/test/analyzer/queries/openapi.test.ts
- packages/oas/test/analyzer/queries/readme.test.ts
Our `xml` query within the `oas/analyzer` library is far too encompassing for all things XML and we need ways to know if an OpenAPI definition uses XML schemas or request bodies but not responses. In order to support I have split apart this query into three new datasets: `xmlSchemas`, `xmlRequests`, and `xmlResponses`. 
The prior `xml` query remains intact and continues to query across all three of these datasets however I am marking it as deprecated and will remove it in a future release.
> feat(oas): splitting apart our `xml` analyzer query into more specific queries

- package-lock.json
- packages/parser/package.json
Some [rdme](https://npm.im/rdme) users are reporting issues with `$ref` parsing failing suddenly after I published a new release of `@readme/openapi-parser` yesterday that included a major version bump of `@apidevtools/json-schema-ref-parser`. Rolling that back to see if it's the cause.
https://github.com/readmeio/rdme/issues/1306
> fix(parser): rolling back our `json-schema-ref-parser` upgrade

- package-lock.json
- packages/parser/package.json
- packages/parser/test/specs/bundling/bundling.test.ts
- packages/parser/test/specs/bundling/nullish-example.yaml
This upgrade `@apidevtools/json-schema-ref-parser` to the latest release and also adds a test for the problem that was surfaced in https://github.com/readmeio/rdme/issues/1306 and fixed in https://github.com/APIDevTools/json-schema-ref-parser/pull/393.
Since this upgrade had to be reverted earlier today due to it being released in a patch release, which was automatically pulled down to all existing rdme versions, since this is a major version bump of `json-schema-ref-parser` I'll do a major version bump of our parser library too. Better safe than sorry.
> chore(deps): upgrading `@apidevtools/json-scheam-ref-parser`

- packages/oas/src/operation/index.ts
- packages/oas/src/operation/lib/operationId.ts
- packages/oas/src/utils.ts
- packages/oas/test/operation/index.test.ts
This exposes our `getOperationId` and `hasOperationID` methods that are a core part of `oas` `Operation` class to be usable outside of the class. I'm doing this because I would like to be able to invoke `getOperationId` without the memory overhead of instantiating new instances of `Oas` and `Operation` to do so.
> feat(oas): exposing utilities for operationId management

- packages/oas-examples/3.0/json/readme-legacy.json
- packages/oas-examples/3.0/yaml/readme-legacy.yaml
- packages/oas-examples/3.1/json/readme.json
- packages/oas-examples/3.1/yaml/readme.yaml
- packages/oas/README.md
- packages/oas/src/analyzer/queries/openapi.ts
- packages/oas/test/analyzer/queries/__snapshots__/openapi.test.ts.snap
- packages/oas/test/analyzer/queries/openapi.test.ts
- packages/oas/test/analyzer/queries/readme.test.ts
- packages/oas/test/extensions.test.ts
- packages/oas/test/index.test.ts
- packages/oas/test/lib/find-schema-definition.test.ts
- packages/oas/test/lib/get-auth.test.ts
- packages/oas/test/operation/index.test.ts
- packages/oas/test/operation/lib/get-response-as-json-schema.test.ts
- packages/oas/test/reducer/index.test.ts
In the process of updating our own API definition in `oas/examples` for v2 of our API I discovered that the queries for `callbacks` and `links` in `oas/analyzer` were improperly picking up schema properties with those names. I've updated those queries to be more accurate.
> fix(oas/analyzer): false positives for callbacks and links

- packages/oas/src/lib/openapi-to-json-schema.ts
- packages/oas/test/__datasets__/response-enums.json
- packages/oas/test/operation/lib/get-response-as-json-schema.test.ts
| 🚥 Resolves CX-989, RM-8112 |
- Replace `.filter(Boolean)` with a targeted predicate to exclude only undefined and blank strings, preserving `false`, `0`, and `null`.
- Update tests to cover boolean/number/null enums.
Impact: Descriptions now correctly include all valid enum values; previously dropped falsy values are retained.
> fix(oas): don’t drop `false`/`0`/`null` when appending enum to description
